(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.StudioRadar=api;})(globalThis,function(){
  'use strict';
  const CATEGORIES=['直播预热','演唱会预热','活动预热','AI商业成片','AI短片叙事','AI镜头实验','AI舞台预演','AI制作方法'];
  const SOURCES=[
    {id:'digitaling',name:'数英项目库',url:'https://www.digitaling.com/projects',categories:['直播预热','活动预热'],note:'国内品牌项目复盘，适合找直播、节日营销和活动机制。'},
    {id:'socialbeta',name:'SocialBeta',url:'https://socialbeta.com/',categories:['直播预热','活动预热'],note:'品牌案例与趋势，适合观察题材、话题和传播节点。'},
    {id:'xinpianchang',name:'新片场',url:'https://universal.xinpianchang.com/',categories:['活动预热','AI商业成片','AI短片叙事'],note:'国内成片与创作人作品，适合看完整叙事和落地质感。'},
    {id:'eventmarketer',name:'Event Marketer',url:'https://www.eventmarketer.com/campaign-finder/',categories:['活动预热'],note:'线下活动与体验营销案例。'},
    {id:'directorslibrary',name:"Directors’ Library",url:'https://directorslibrary.com/',categories:['活动预热','AI短片叙事'],note:'导演视角的影片策展，适合练叙事与镜头语言。'},
    {id:'shotdeck',name:'ShotDeck',url:'https://shotdeck.com/',categories:['AI镜头实验','AI制作方法'],note:'电影镜头检索库，适合定义摄影、灯光、色彩和构图。'},
    {id:'frameset',name:'Frame Set · Motions',url:'https://frameset.app/search',categories:['活动预热','AI镜头实验','AI制作方法'],note:'运镜、转场和剪辑技法检索。系统只保存来源链接与自己的中文观察，不整站复制第三方影片和文字。'},
    {id:'stash',name:'Stash',url:'https://www.stashmedia.tv/',categories:['AI商业成片','AI镜头实验','AI制作方法'],note:'动画、VFX与新型影像作品。'},
    {id:'momentfactory',name:'Moment Factory',url:'https://momentfactory.com/',categories:['演唱会预热','AI舞台预演'],note:'沉浸式体验、舞台与声光电项目。'},
    {id:'treatmentstudio',name:'Treatment Studio',url:'https://www.treatmentstudio.com/work/',categories:['演唱会预热','AI舞台预演'],note:'演出视觉、巡演舞台与大屏幕内容。'},
    {id:'northhouse',name:'NorthHouse',url:'https://www.northhousecreative.com/',categories:['演唱会预热','AI舞台预演'],note:'演唱会、舞台影像与实时视觉。'},
    {id:'livedesign',name:'Live Design',url:'https://www.livedesignonline.com/concerts',categories:['演唱会预热','AI舞台预演'],note:'演出灯光、音响、视频与制作技术。'},
    {id:'runwayfestival',name:'Runway AI Film Festival',url:'https://aif.runwayml.com/',categories:['AI短片叙事','AI镜头实验'],note:'AI影片节入选作品，重点看完整叙事，不只看模型测试。'},
    {id:'somewhile',name:'SOMEWHILE',url:'https://www.somewhile.cn/',categories:['AI商业成片','AI短片叙事'],note:'国内AI创意影像与行业资讯线索。'},
    {id:'ailine',name:'AILINE',url:'https://ailine.cloud/',categories:['AI商业成片','AI制作方法'],note:'AI影像案例与创作流程线索。'},
    {id:'lair',name:'LAIR AIGC',url:'https://lair-aigc.com/',categories:['AI短片叙事','AI镜头实验'],note:'AIGC创作活动与作品线索。'},
    {id:'vjshi',name:'光厂 AIGC 案例',url:'https://www.vjshi.com/cases/so/aigc',categories:['AI商业成片','AI镜头实验'],note:'国内AIGC影像案例索引，需区分商业交付和纯效果测试。'},
    {id:'deepshow',name:'Deepshow',url:'https://deepshow.tech/duanju.html',categories:['AI短片叙事','AI制作方法'],note:'AI短剧与制作流程线索。'},
    {id:'krea',name:'Krea',url:'https://www.krea.run/features/ai-video-generator',categories:['AI镜头实验','AI制作方法'],note:'AI视频工具与效果测试，不等同于真实商业交付。'}
  ];
  const MOTIONS=[
    {id:'motion-locked',name:'固定镜头',en:'Locked-off',symbol:'●',description:'机位完全不动，让人物、场面调度和画内变化承担注意力。',effect:'克制、观察、庄重，也能让突发动作更有冲击。',execution:'三脚架锁死云台；先确定画内运动路线和构图层次。',use:'自述、仪式开场、对称舞台、情绪停顿。',avoid:'画面没有内部变化时容易僵；不要把“稳定”误当成“没有设计”。'},
    {id:'motion-push-in',name:'推进',en:'Push-in / Dolly-in',symbol:'→ ●',description:'摄影机真实靠近主体，透视和前后景关系同时发生变化。',effect:'加强关注、进入人物内心、揭示关键信息。',execution:'轨道、滑轨、稳定器或手持缓慢前进；提前设计焦点与停点。',use:'人物决定、情绪转折、产品揭晓、口号前蓄力。',avoid:'速度必须服务情绪；不能用数码放大冒充真实推进的空间感。'},
    {id:'motion-pull-out',name:'拉远',en:'Pull-out / Dolly-out',symbol:'● →',description:'摄影机离开主体，逐步显露环境、关系或人物的处境。',effect:'孤独、释然、结束感，也适合从细节揭示大场面。',execution:'先锁定起幅重点，再确保退路、焦点和最终构图准确。',use:'片尾、舞台全貌、人物被环境吞没、反转揭示。',avoid:'只退不揭示新信息会显得空；结尾画面要有明确落点。'},
    {id:'motion-truck',name:'横向移动',en:'Truck / Lateral move',symbol:'← ● →',description:'摄影机与主体平行横移，用前景遮挡和背景位移制造层次。',effect:'流动、巡视、节奏感，适合展示空间和队伍关系。',execution:'轨道、车拍、稳定器或滑轨；寻找可形成视差的前中后景。',use:'走场、货架、团队集结、时装展示、连续动作。',avoid:'背景太平会失去运动感；横移方向要匹配人物视线和剪辑轴线。'},
    {id:'motion-follow',name:'跟拍',en:'Tracking / Follow',symbol:'● ⇢ 人',description:'摄影机跟随人物移动，让观众与角色共享路径和即时发现。',effect:'陪伴、代入、紧迫、真实现场感。',execution:'先排人物速度、转弯和遮挡，再选择手持、稳定器或车辆。',use:'主播入场、幕后纪实、任务推进、长廊与通道。',avoid:'不能只顾追人而丢失空间信息；注意跟焦、脚步和安全路线。'},
    {id:'motion-pan',name:'水平摇摄',en:'Pan',symbol:'↔',description:'机位不移动，镜头水平旋转，连接两个信息点或追随横向动作。',effect:'发现、交代关系、转移注意力，也可制造速度。',execution:'确定起幅、落幅和旋转速度；让动作触发摇摄而不是无目的扫景。',use:'人物对看、舞台左右区、空间揭示、动作接力。',avoid:'中途没有视觉动机会像监控；过快易模糊，过慢易泄气。'},
    {id:'motion-tilt',name:'垂直摇摄',en:'Tilt',symbol:'↕',description:'机位不移动，镜头上下旋转，用高度关系完成揭示或强调。',effect:'建立量级、敬畏、压迫，或从细节转向人物。',execution:'设计明确的上下信息关系；控制建筑垂直线和人物头部安全区。',use:'舞台装置、人物全身、服装细节、奖杯或灯阵揭晓。',avoid:'不要从脚到头机械扫描；落幅必须比起幅提供更重要的信息。'},
    {id:'motion-orbit',name:'环绕',en:'Orbit / Arc',symbol:'↻ ●',description:'摄影机围绕主体走弧线，使背景连续变化并强化主体中心。',effect:'英雄化、浪漫、关系变化、时间被拉长。',execution:'明确圆心、半径、速度和焦段；人物可静止或反向转身增强变化。',use:'主角登场、双人关系、产品英雄镜头、高潮定格。',avoid:'空间狭窄或背景杂乱时容易穿帮；不要无意义绕满一圈。'},
    {id:'motion-pedestal',name:'升降',en:'Pedestal / Boom',symbol:'⇅ ●',description:'摄影机整体上下移动，机位高度改变但观看方向相对稳定。',effect:'从遮挡中出现、建立地位、连接地面与舞台。',execution:'升降台、摇臂、稳定器或人工抬升；预先核对顶部和地面安全。',use:'人物站起、舞台亮相、商品陈列、空间纵深揭示。',avoid:'不同于垂直摇摄；升降时要处理视差、焦点和设备承重。'},
    {id:'motion-crane',name:'摇臂大升降',en:'Crane / Jib',symbol:'⌒ ↑',description:'以机械臂完成大范围空间位移，可同时升降、前后和转向。',effect:'宏大、庆典、收束、从个人扩展到群体。',execution:'先画运动轨迹和安全区，明确开头、高潮与落点三个关键位置。',use:'专场开场、全场集结、舞台转场、结尾烟火。',avoid:'设备感不能代替情绪；吊臂路线、人员和灯具必须安全隔离。'},
    {id:'motion-handheld',name:'手持',en:'Handheld',symbol:'≈ ●',description:'保留身体传递给摄影机的微小不稳定，形成在场和呼吸感。',effect:'真实、紧张、亲密、纪录性。',execution:'用身体而不是手腕吸收震动；先规定晃动幅度、距离和跟随对象。',use:'幕后、冲突、奔跑、纪录式自述、拥挤现场。',avoid:'手持不是随便晃；过度抖动会破坏信息和观看舒适度。'},
    {id:'motion-steadicam',name:'稳定器长镜头',en:'Gimbal / Steadicam',symbol:'—●—',description:'在人物与空间之间连续穿行，同时保持相对平滑的观看体验。',effect:'沉浸、流畅、精心调度、一次完成的现场感。',execution:'按秒排走位、焦点、灯光和隐藏工作人员；准备可剪切的遮挡点。',use:'入场、后台到舞台、空间漫游、多人接力。',avoid:'长并不等于好；每一段必须产生新信息，不能为了炫技拖时长。'},
    {id:'motion-slider',name:'短距滑移',en:'Slider / Parallax',symbol:'| ⇆ ●',description:'在很短距离内横移或斜移，用前景制造精致视差。',effect:'细腻、产品感、轻微揭示、画面呼吸。',execution:'前景要靠近镜头，主体保持明确；控制滑轨端点和起停缓动。',use:'产品、服装细节、桌面、美术陈设、人物静态肖像。',avoid:'没有前景层次时几乎看不出运动；不要每个镜头都同速滑动。'},
    {id:'motion-zoom',name:'光学变焦',en:'Zoom',symbol:'[ ● ]',description:'机位不动，通过改变焦距放大或缩小画面，空间透视不会像真实位移那样变化。',effect:'观察、突发强调、复古电视感，也能制造不安。',execution:'选择有顺滑变焦环的镜头，设计速度与焦点补偿。',use:'舞台直播、喜剧反应、远处细节、快速信息强调。',avoid:'不要把所有推进都用变焦替代；数码裁切会损失画质。'},
    {id:'motion-dolly-zoom',name:'推拉变焦',en:'Dolly Zoom',symbol:'→ [ ] ←',description:'摄影机位移与反向变焦同时发生，让主体大小近似不变、背景透视剧烈改变。',effect:'眩晕、世界失衡、人物顿悟或危机。',execution:'先确定主体尺寸，标记轨道距离与对应焦段，跟焦员同步。',use:'心理冲击、重大揭示、夸张喜剧节点。',avoid:'技术要求高且语义强烈；普通情绪不要滥用。'},
    {id:'motion-whip-pan',name:'甩镜',en:'Whip Pan',symbol:'⇝',description:'高速摇摄产生运动模糊，可连接方向相似的两个场景或动作。',effect:'突然、加速、喜剧、无缝转场。',execution:'两端都要设计清晰起落幅；以相同方向、速度和模糊量匹配剪辑。',use:'人物切换、地点跳转、口号节奏、动作接力。',avoid:'只有模糊没有匹配逻辑会显得廉价；注意观众眩晕。'},
    {id:'motion-roll',name:'翻滚',en:'Camera Roll',symbol:'⟳',description:'摄影机绕镜头轴旋转，改变地平线方向。',effect:'失重、疯狂、梦境、世界规则被打破。',execution:'确定旋转中心、角度与恢复时机；美术线条越明确效果越强。',use:'梦境、AI段落、心理崩塌、特殊转场。',avoid:'语义过强，不适合普通叙事；必须考虑竖屏观看和字幕方向。'},
    {id:'motion-drone',name:'航拍穿越',en:'Drone / FPV',symbol:'⌁ ⇢',description:'从空中或狭窄路径完成大尺度移动，把地理、速度和空间关系一次交代。',effect:'规模、自由、冲击、不可替代的路径体验。',execution:'常规航拍重构图，FPV重路径；都要先勘景、报批并设计失控预案。',use:'场馆外观、城市开场、建筑穿越、户外活动。',avoid:'天气、禁飞区、人员安全和画面抖动优先于炫技。'},
    {id:'motion-pov',name:'主观运动',en:'POV',symbol:'◎ ⇢',description:'让镜头代表人物眼睛或身体位置，把观看者直接放进动作。',effect:'代入、压迫、游戏感、第一人称发现。',execution:'明确“谁在看”、视线高度、呼吸节奏和手部/身体证据。',use:'任务片、体验式直播预热、追逐、开门揭示。',avoid:'没有人物线索会变成无主视角；快速运动要控制眩晕。'}
  ];
  const CASES=[
    {id:'duxiaoman-521',title:'度小满521答谢音乐会',url:'https://www.digitaling.com/projects/346030.html',poster:'https://file.digitaling.com/eImg/cover/20250730/20250730191359_78719.png',site:'数英',category:'演唱会预热',type:'商业交付案例',goal:'情感造势、活动预约',mechanism:'把品牌答谢转化为一场有情感仪式的音乐事件。',hook:'从一个可感知的感谢瞬间或人物关系切入，具体画面待看片核对。',arc:'个人情感—集体回应—活动期待。',craft:'重点拆舞台仪式、人物近景和现场氛围的关系。',cover:'人物情绪+音乐会名称+日期信息。',transfer:'把“卖货前的预热”转成“用户与主播互相赶赴”。',avoid:'不照搬演出规模和品牌语言。',ai:'可用AI预演舞台气氛、灯光节奏和封面方向。',risk:'演出授权、音乐版权、嘉宾肖像需单独确认。'},
    {id:'jd-murder-live',title:'京东电器剧本杀直播',url:'https://www.digitaling.com/projects/224580.html',poster:'https://file.digitaling.com/eImg/cover/20221008/20221008184216_25027.jpg',site:'数英',category:'直播预热',type:'商业交付案例',goal:'吸睛、观看预约、直播互动',mechanism:'用类型叙事和角色任务包装直播利益点。',hook:'直接抛出异常事件或谜题，让观众立即进入任务。',arc:'谜题—搜证—反转—直播入口。',craft:'重点看置景、道具线索、角色造型和节奏剪辑。',cover:'一个谜题文案+关键道具+主播角色造型。',transfer:'把产品机制变成观众可参与的任务。',avoid:'不让世界观设定压过直播利益和日期。',ai:'可用AI做类型化概念图和开场8秒氛围预演。',risk:'剧情需避免误导，商品权益信息必须与最终机制一致。'},
    {id:'ai-12h-live',title:'《被AI硬控的一天》12小时直播',url:'https://www.digitaling.com/projects/372525.html',poster:'https://file.digitaling.com/eImg/cover/20260713/20260713173016_83316.jpg',site:'数英',category:'AI商业成片',type:'商业交付案例',goal:'话题、观看时长、产品体验',mechanism:'把AI从工具变成控制一天行动的叙事角色。',hook:'先展示一个反常指令或不可退出的规则。',arc:'新鲜—失控—适应—完成挑战。',craft:'真实直播证据与AI界面、字幕和视觉效果交替。',cover:'强冲突标题+人物被“操控”的瞬间。',transfer:'让AI成为事件机制，不只是生成素材。',avoid:'不把假的AI能力宣传为真实功能。',ai:'AI为创意机制与视觉制作的双重部分，需看项目说明核对。',risk:'AI生成内容、产品功能表述和直播安全边界。'},
    {id:'breaking2',title:'Nike Breaking2',url:'https://www.wk.com/work/nike-breaking2/',poster:'https://images.ctfassets.net/ckso4uqg4vio/IsJaZ0cDO6q4WcWACK28o/a637484c22b2b6ead8ab16015db8ffd0/1_gOgkX4L9hwdPXxHKFRdyfQ.jpeg?w=1200&h=630&fm=jpg',site:'Wieden+Kennedy',category:'活动预热',type:'商业交付案例',goal:'造势、事件观看、品牌精神',mechanism:'用一个清晰、几乎不可能的目标串起人物、训练和直播事件。',hook:'目标数字和人类极限冲突立即出现。',arc:'不可能—准备—临场—见证。',craft:'训练细节、数据可视化、人物表情和事件纪录融合。',cover:'一个目标数字+一个决定性人物画面。',transfer:'为专场建立一个全员共享的清晰任务。',avoid:'不空洞复制“挑战极限”，必须有真实证据和规则。',ai:'可用AI预演数据屏、路径空间和时间压力视觉。',risk:'纪录性内容不能由AI伪造，数据需有来源。'},
    {id:'redbull-stratos',title:'Red Bull Stratos',url:'https://www.redbull.com/us-en/the-science-of-red-bull-stratos',poster:'https://img.redbull.com/images/c_fill,g_auto,w_1200,h_630/f_auto,q_auto/redbullcom/2024/2/26/by97kzx7tozkscadp0jn/red_bull_rocket_drone_vs_oracle_f1_car',site:'Red Bull',category:'活动预热',type:'品牌事件案例',goal:'全球事件造势、直播见证',mechanism:'把科学准备、人物风险与一次不可重复的直播时刻合为一条悬念线。',hook:'用高度、风险或临界瞬间立即建立量级。',arc:'科学准备—升空—临界等待—见证。',craft:'宏观尺度、人物呼吸、控制中心与数据界面并置。',cover:'极端尺度的单一主视觉+完成时刻。',transfer:'用“只此一次”的事件感提升预热强度。',avoid:'不用虚构危险欺骗观众。',ai:'可做极端尺度概念预演，但真实事件证据必须保留。',risk:'安全、科学数据、纪录真实性。'},
    {id:'tomorrowland-winter',title:'Tomorrowland Winter Trailer',url:'https://www.tomorrowland.com/article/tomorrowland-winter-trailer/',poster:'https://www.tomorrowland.com/home/media/abgv_7bci2UF6EN2_Scherm%C2%ADafbeelding2026-03-16om17.29.00.png?auto=format,compress&rect=260,0,2032,1067&w=2400&h=1260',site:'Tomorrowland',category:'演唱会预热',type:'完整成片参考',goal:'世界观造势、售票期待',mechanism:'先让观众相信一个节日世界，再把演出信息变成进入世界的入口。',hook:'用一个超现实地标或异常天气快速建立世界观。',arc:'发现入口—穿越场景—人群集结—节日揭晓。',craft:'广角地貌、奇观置景、快慢节奏反差与音乐高潮。',cover:'世界观地标+小人物比例+活动标识。',transfer:'为专场建立可持续复用的世界观符号。',avoid:'不只堆奇观，要让场景与主播、产品或活动任务发生关系。',ai:'AI适合做世界观气氛、场景转换和舞台延展预演。',risk:'原品牌世界观与音乐素材不可直接搬用。'},
    {id:'playstation-concert',title:'PlayStation The Concert',url:'https://www.northhousecreative.com/projects/playstation-the-concert',poster:'https://images.ctfassets.net/ovgmkgydma71/4gWHKAXZV4HGULSbnfeAA0/378f38f5327c2064f46c623320761366/PLAYSTATION_THE_CONCERT_13.jpg?fit=fill&h=759&w=1356',site:'NorthHouse',category:'AI舞台预演',type:'舞台视觉案例',goal:'演出造势、IP记忆唤起',mechanism:'把熟悉的IP世界转译为现场屏幕、灯光与音乐的空间体验。',hook:'以高识别度符号和声音记忆快速唤起粉丝。',arc:'IP唤醒—空间扩展—人群共振—演出期待。',craft:'重点拆屏幕比例、灯光方向、视觉节奏与舞台人物关系。',cover:'IP符号+舞台尺度+演出名称。',transfer:'先确定一组可识别的视觉语法，再展开多首曲目或多条预热片。',avoid:'不直接使用受保护的IP视觉和音乐。',ai:'适合用AI做舞台概念、屏幕内容和灯光节奏预演，最终需按真实屏幕尺寸校验。',risk:'IP授权、音乐版权、屏幕规格与现场安全。'},
    {id:'runway-aiff',title:'Runway AI Film Festival 入选作品库',url:'https://aif.runwayml.com/',poster:'https://aiff.runwayml.com/opengraph-image.png?4df29fdf42d71751',site:'Runway',category:'AI短片叙事',type:'AI完整成片合集',goal:'叙事方法、AI成片质量标杆',mechanism:'不把AI当特效，而是观察它如何支撑完整的角色、观点和结尾。',hook:'每部作品单独记录，先拆前8秒是画面奇观、人物悬念还是声音钩子。',arc:'必须看完整片后再写，不以单张截图代替叙事判断。',craft:'重点检查角色一致性、镜头连续、声音、剪辑和AI瑕疵的处理。',cover:'记录作品的核心命题，而不只是最奇观的一帧。',transfer:'建立“这个AI镜头为什么必须存在”的评估习惯。',avoid:'不把影展作品误当为实时可复制的工具演示。',ai:'AI参与类型与模型需按每部作品的创作者说明核对。',risk:'影展作品仅作方法研究，不下载、不搬用角色或画面。'},
    {id:'adidas-find-your-rhythm',title:'Adidas · Find Your Rhythm',url:'https://directorslibrary.com/2024/latest/campaigns/find-your-rhythm-adidas/',poster:'https://directorslibrary.com/wp-content/uploads/2024/02/Find-Your-Rhythm-Adidas-1.png',site:"Directors’ Library",category:'活动预热',type:'16mm摄影参考',visualFocus:'摄影质感',goal:'把普通城市生活拍出身体节奏与品牌活力',mechanism:'用人物动作、街道秩序和剪辑节拍，把“找到自己的节奏”变成可见的生活流。',hook:'看片时重点观察：前8秒如何用局部动作、环境声和快速建立的人物状态抓住注意力。',arc:'城市观察—动作接力—节奏形成—品牌收束。',craft:'16mm拍摄；重点拆颗粒、自然光容错、手持距离、动作衔接和环境色控制，而不是只截单帧。',cover:'人物动作定格+城市环境层次，避免堆太多文案。',transfer:'把主播走场、备播、团队动作拍成有节奏的真实工作流。',avoid:'不照搬街头人物、服装和具体动作编排。',ai:'可用AI预演色彩与动作节奏，真实颗粒、运动模糊和肤色仍需摄影测试。',risk:'街拍肖像、场地与音乐授权需确认。'},
    {id:'hello-miss-johnson',title:'Jack Harlow · Hello Miss Johnson',url:'https://directorslibrary.com/2024/latest/music-videos/hello-miss-johnson-jack-harlow/',poster:'https://directorslibrary.com/wp-content/uploads/2024/11/Hello-Miss-Johnson-Jack-Harlow-1.png',site:"Directors’ Library",category:'演唱会预热',type:'4:3构图参考',visualFocus:'构图画幅',goal:'研究方画幅如何集中人物关系与喜剧信息',mechanism:'用固定的4:3视觉规则建立统一世界，让人物、空间和后期效果保持同一种观看语气。',hook:'先观察人物与空间关系如何在窄画幅内迅速交代，而非只追求复古比例。',arc:'人物进入—空间规则建立—视觉变化—表演收束。',craft:'1.33:1数字拍摄；重点拆头顶留白、双人站位、门框/窗框套构图和近景切换。',cover:'单一人物姿态+强轮廓空间，画幅本身就是识别点。',transfer:'适合自述片、人物宣言或“面对镜头说一件事”的封闭空间方案。',avoid:'4:3不是滤镜，必须同步设计场景宽度、人物调度和字幕安全区。',ai:'AI参考图先锁定1.33:1，再转9:16时重新校验构图。',risk:'音乐、人物造型和原片特效不可直接复制。'},
    {id:'hard-dreams',title:'Gesaffelstein · Hard Dreams',url:'https://directorslibrary.com/2024/latest/music-videos/hard-dreams-gesaffelstein/',poster:'https://directorslibrary.com/wp-content/uploads/2024/05/Hard-Dreams-Gesaffelstein-1.png',site:"Directors’ Library",category:'演唱会预热',type:'黑白影像参考',visualFocus:'灯光影调',goal:'研究低色彩条件下如何依靠光、质感和身体制造压迫感',mechanism:'削弱颜色，把注意力集中到人物轮廓、材质反光和空间明暗关系。',hook:'看片时重点拆第一束光如何定义人物，而不是把“暗”误解成欠曝。',arc:'黑暗建立—身体显现—空间压迫—能量释放。',craft:'重点观察Łukasz Żal的光位、人物轮廓、烟雾层次、黑位细节和高光控制，并记录美术材质如何接光。',cover:'高反差人物轮廓+极少文字。',transfer:'用于冠军、决战、回归类预热时，以光线变化承担人物心理转折。',avoid:'不要用纯黑和烟雾代替场景逻辑；暗部必须保留可播放细节。',ai:'可用AI做光位预演，但需用真实机型测试暗部噪点和LED摩尔纹。',risk:'造型、表演和音乐语气需完全重构。'},
    {id:'prelude-to-ecstacy',title:'The Last Dinner Party · Prelude to Ecstacy',url:'https://directorslibrary.com/2024/latest/music-videos/prelude-to-ecstacy/',poster:'https://directorslibrary.com/wp-content/uploads/2024/10/Prelude-to-Ecstacy-1.png',site:"Directors’ Library",category:'演唱会预热',type:'叙事美术参考',visualFocus:'美术置景',goal:'研究一个完整美术世界如何支撑人物群像与舞蹈叙事',mechanism:'把乐队成员放入带规则的“华丽而危险”空间，让服装、置景和表演共同讲故事。',hook:'前8秒先建立场所规则、人物身份与一处不安细节。',arc:'进入学院—秩序展示—欲望失控—群像高潮。',craft:'重点拆舞蹈空间的纵深、重复陈设、暖冷区域、服装色块与群演调度；记录哪些部分可用棚拍完成。',cover:'群像层级+核心场景符号，避免只选最华丽的服装。',transfer:'适合专场建立统一世界观，再让多条预热视频共享同一套场景语法。',avoid:'不复制学校、宗教或古典服装表面符号。',ai:'AI先做场景分区和色彩方案，再按真实棚高、通道、消防与预算收敛。',risk:'群演、服化道与搭景工期要单独估算。'},
    {id:'abracadabra',title:'Lady Gaga · Abracadabra',url:'https://directorslibrary.com/2025/latest/music-videos/abracadabra-lady-gaga/',poster:'https://directorslibrary.com/wp-content/uploads/2025/02/Abracadabra-Lady-Gaga-1.jpg',site:"Directors’ Library",category:'活动预热',type:'群舞视听参考',visualFocus:'人物调度',goal:'研究大规模群舞如何保持主角识别和视觉秩序',mechanism:'以明暗对抗为视觉规则，让服装、灯光、舞蹈阵型和剪辑服务同一个冲突。',hook:'先用一组清晰阵型与主角位置建立规则，再逐步增加密度。',arc:'规则建立—阵型对抗—能量加速—主角定格。',craft:'重点拆主角与群演的亮度差、色块分组、阵型变化、机位高度和运动镜头的落点。',cover:'主角居中+两侧阵营/色块对抗。',transfer:'适合团队集结、主播登场和大型专场口号段落。',avoid:'不照搬舞蹈、服装或“黑白阵营”设定；先明确自己的冲突。',ai:'可用AI做阵型和服装色块预演，但真人走位必须按场地实排。',risk:'群演安全、舞蹈版权、服装与灯光同步。'},
    {id:'lewis-capaldi-live',title:'Lewis Capaldi · European Tour',url:'https://www.northhousecreative.com/projects/lewis-capaldi',poster:'https://framerusercontent.com/images/1Axp4HQ7XNqjakshQhNTFjlZaFs.webp?width=1500&height=844',site:'NorthHouse',category:'演唱会预热',type:'现场摄影与屏幕参考',visualFocus:'现场影像',goal:'让大场馆仍保留亲密、电影化的人物感',mechanism:'用克制的舞台结构、现场摄像和有纹理的投影层包围表演，而不让效果压过人物。',hook:'先用一个强现场近景建立人与观众的距离，再让屏幕与灯光扩张空间。',arc:'亲密近景—纹理铺开—情绪放大—回到人物。',craft:'重点拆现场机位、长焦近景、LED与投影亮度平衡、Live Camera效果和灯光配合。',cover:'真实表演近景+一层有质感的舞台背景。',transfer:'适合主播自述或温情片：先有人，再有舞台奇观。',avoid:'不为了“高级”堆叠屏幕效果，必须保证肤色与眼神可读。',ai:'用AI预演屏幕内容与灯光气氛，现场摄像延迟、曝光和色温要实测。',risk:'LED频闪、摩尔纹、屏幕亮度和现场摄影曝光。'},
    {id:'billie-hmhas-tour',title:'Billie Eilish · Hit Me Hard and Soft Tour',url:'https://momentfactory.com/products/billie-eilish-hit-me-hard-and-soft-the-tour',poster:'https://cdn.shopify.com/s/files/1/0642/9625/5685/files/Moment_Factory_Custom_Concerts_and_Shows_Billie_Eilish_Hard_and_Soft_Tour_115-WS.jpg?v=1734470287',site:'Moment Factory',category:'演唱会预热',type:'360舞台参考',visualFocus:'舞台声光',goal:'研究巨型场馆如何通过360舞台制造亲密感和视觉变化',mechanism:'把LED地面、升降平台、塔体、悬挂屏与激光组合成可随歌曲情绪变化的空间。',hook:'用极简人物尺度与巨大空间的反差，快速建立演出量级。',arc:'亲密—空间变形—能量爆发—情绪回落。',craft:'重点拆360观众视角、俯拍机位、LED地面反光、激光层次与人物追光；观察不同歌曲如何更换空间规则。',cover:'人物小比例+完整舞台几何形态。',transfer:'专场先确定一套可变化的核心舞台结构，再为多条视频切换灯光与屏幕内容。',avoid:'不照搬设备规模；先按真实场地和预算找到一个主装置。',ai:'适合用AI和3D预演不同观众角度，最终以真实屏幕、吊点和安全数据为准。',risk:'吊挂、激光、升降台、观众视线与广播机位。'},
    {id:'kings-coronation-concert',title:"The King's Coronation Concert",url:'https://www.northhousecreative.com/projects/the-kings-coronation-concert',poster:'https://images.ctfassets.net/ovgmkgydma71/473UD7KPHd2VPV3iKJAHox/c8b12acba7504f0565535ec909f52eed/133110_Coronation-2.png?w=1200',site:'NorthHouse',category:'AI舞台预演',type:'建筑投影与预演参考',visualFocus:'色彩美术',goal:'研究怎样把个人绘画语言扩展成大型舞台视觉系统',mechanism:'以水彩质感作为统一视觉母题，在不同节目、屏幕和建筑表面之间维持整体性。',hook:'先建立一个能被立即识别的材质或色彩母题，再让规模逐步展开。',arc:'材质出现—建筑扩张—节目变化—整体回归。',craft:'重点拆金色、绿色、水彩肌理、漏光与建筑投影的关系，以及摄影机从多个角度如何仍保持画面可读。',cover:'建筑轮廓+一种主材质，不用把所有节目元素塞在一起。',transfer:'为中秋、双十一等专场先找一个属于人物和节日的视觉母题，再延展到舞台、封面和视频。',avoid:'不复制王室、水彩或城堡符号；借鉴的是“单一母题统领全场”。',ai:'项目使用Unreal预演不同视角、光线和天气；你的场景库也应按尺寸图做同类落地校验。',risk:'建筑亮度、天气、投影位置、机位与现场许可。'},
    {id:'fkj-world-tour',title:'FKJ · World Tour',url:'https://www.northhousecreative.com/projects/fkj',poster:'https://images.ctfassets.net/ovgmkgydma71/5HW03JqeLyZoYa2kQlf87v/4e0c863e61727749c6d7b0233dd23239/146566_FKJ_AmericaTour_Image021.jpg?w=1200',site:'NorthHouse',category:'演唱会预热',type:'场景延展参考',visualFocus:'场景设计',goal:'研究一间私人空间如何通过屏幕逐步扩展成超现实世界',mechanism:'把舞台设计成音乐人的工作室，再让“窗外景观”从真实自然逐渐失真。',hook:'先让观众看懂这是一个真实房间，再在窗外放入第一处异常变化。',arc:'私人房间—自然延展—现实变形—抽象高潮。',craft:'重点拆窗框构图、室内暖光、屏幕景别、人物与背景比例，以及实时视觉怎样跟随节拍而不割裂。',cover:'人物工作室+一扇发生变化的窗。',transfer:'适合“从个人出发走向大世界”的主播、纪录或个人创作主题。',avoid:'不复制丛林与工作室布景；先找属于主人公的真实私人空间。',ai:'AI可生成窗外世界的阶段变化，真实场景与屏幕色温、黑位必须统一。',risk:'LED与实景交界、镜头视差、屏幕刷新率和现场同步。'}
  ];
  function normalizedURL(value){try{const u=new URL(String(value||'').trim());u.hash='';['utm_source','utm_medium','utm_campaign','utm_term','utm_content'].forEach(k=>u.searchParams.delete(k));u.pathname=u.pathname.replace(/\/+$/,'')||'/';return u.href;}catch{return '';}}
  function duplicate(items,item){const url=normalizedURL(item.url||item.link);return (items||[]).find(a=>a.radarSourceId===item.id||(url&&normalizedURL(a.link)===url))||null;}
  function notes(item,scope){return [
    '【案例雷达线索·打开来源看片后请核对】',
    `项目类型：${item.category||'待分类'} · ${item.type||'案例线索'}`,
    `目标：${item.goal||'待补充'}`,
    `一句话创意机制：${item.mechanism||'待看片后补充'}`,
    `开场8秒：${item.hook||'待看片后补充'}`,
    `情绪／故事弧：${item.arc||'待看片后补充'}`,
    `摄影／美术／舞台声光：${item.craft||'待看片后补充'}`,
    `封面／主视觉：${item.cover||'待看片后补充'}`,
    `可迁移：${item.transfer||'待补充'}`,
    `不可照搬：${item.avoid||'待补充'}`,
    `AI参与：${item.ai||'待核对'}`,
    `落地／版权／肖像风险：${item.risk||'待核对'}`,
    `适配建议：${scope==='xinxuan'?'用于辛选工作时，先改写为主播关系、商品机制和直播日期的真实任务。':'用于个人创作时，保留方法，换成自己真正想表达的人物与命题。'}`
  ].join('\n');}
  function caseToAesthetic(item,uid,scope='personal'){
    const now=new Date().toISOString();return {id:uid(),name:item.title,kind:'aesthetic',category:item.category.startsWith('AI')?'AI参考':item.category==='演唱会预热'?'舞台声光电':'广告TVC',tags:[item.category,item.type||'案例线索','案例雷达'],notes:notes(item,scope),requirements:notes(item,scope),link:normalizedURL(item.url),externalPreview:item.poster||'',sourceSite:item.site||new URL(item.url).hostname,sourceUsage:'link-only',files:[],coverId:null,favorite:true,usedIn:[],folderIds:[],radarSourceId:item.id,radarKind:'case',createdAt:now,updatedAt:now};
  }
  function sourceToAesthetic(item,uid){
    const now=new Date().toISOString();return {id:uid(),name:item.name,kind:'aesthetic',category:item.categories.some(c=>c.startsWith('AI'))?'AI参考':'其他',tags:[...item.categories,'案例网站','案例雷达'],notes:`【案例来源】${item.note}\n使用时请手动打开链接、挑选单个作品，再将成片截图、参考重点和不可照搬部分补齐。本系统不会自动登录或抓取网站。`,requirements:'',link:normalizedURL(item.url),sourceSite:item.name,sourceUsage:'link-only',files:[],coverId:null,favorite:true,usedIn:[],folderIds:[],radarSourceId:item.id,radarKind:'source',createdAt:now,updatedAt:now};
  }
  function motionToAesthetic(item,uid){
    const now=new Date().toISOString(),text=[`【中文运镜参考卡·${item.en}】`,`定义：${item.description}`,`画面感受：${item.effect}`,`拍摄执行：${item.execution}`,`适合：${item.use}`,`避免：${item.avoid}`,'案例入口：Frame Set · Motions（请在原站内搜索英文运镜名，具体影片与GIF仅作私人创意参考）'].join('\n');
    return {id:uid(),name:`运镜｜${item.name} · ${item.en}`,kind:'aesthetic',category:'分镜参考',tags:['运镜参考','摄影调性',item.name,item.en,'Frame Set入口'],notes:text,requirements:text,link:'',sourceSite:'Frame Set · Motions',sourceUsage:'description-only',files:[],coverId:null,favorite:true,usedIn:[],folderIds:[],radarSourceId:item.id,radarKind:'motion-guide',createdAt:now,updatedAt:now};
  }
  function caseToTopic(item,topicFactory,scope='personal'){
    const t=topicFactory(item.title+' · 我的转化');t.idea=[`来源：${item.title}`,`可迁移机制：${item.transfer||item.mechanism||'待拆解'}`,scope==='xinxuan'?'改写要求：转化为当前主播、商品机制、直播日期和真实资源可支撑的新创意。':'改写要求：只保留方法，转化为自己真正想表达的人物和命题。'].join('\n');t.inspirationSource=normalizedURL(item.url);t.form=item.category;t.motif=item.mechanism||'';t.exploration=item.avoid||'';t.quick.fields.outline=item.mechanism||'';t.radarSource={id:item.id,title:item.title,url:normalizedURL(item.url),category:item.category};return t;
  }
  function daily(items,date=new Date(),count=3){const day=Math.floor(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())/86400000),out=[];for(let i=0;i<Math.min(count,items.length);i++)out.push(items[(day+i*3)%items.length]);return out;}
  function mobileDaily(items,date=new Date(),count=3){const visual=items.filter(item=>item.visualFocus),general=items.filter(item=>!item.visualFocus),visualCount=Math.min(Math.max(count-1,0),visual.length),out=daily(visual,date,visualCount);for(const item of daily(general,new Date(date.getTime()+86400000),count-visualCount)){if(!out.some(existing=>existing.id===item.id))out.push(item);}return out.slice(0,count);}
  function mobileBatch(items,seenIds=[],seed=0,count=3){
    const unique=[...new Map((items||[]).filter(item=>item?.id).map(item=>[item.id,item])).values()],valid=new Set(unique.map(item=>item.id)),previous=(seenIds||[]).filter(id=>valid.has(id)),seen=new Set(previous);let available=unique.filter(item=>!seen.has(item.id)),reset=false;
    if(available.length<Math.min(count,unique.length)){reset=true;const recent=new Set(previous.slice(-count));available=unique.filter(item=>!recent.has(item.id));seen.clear();if(available.length<Math.min(count,unique.length))available=unique.slice();}
    const hash=value=>{let h=(Number(seed)||0)>>>0;for(const char of String(value)){h=Math.imul(h^char.charCodeAt(0),2654435761)>>>0;}return h;},rank=list=>[...list].sort((a,b)=>hash(a.id)-hash(b.id)),visual=rank(available.filter(item=>item.visualFocus)),general=rank(available.filter(item=>!item.visualFocus)),out=[],target=Math.min(count,unique.length);
    out.push(...visual.slice(0,Math.min(2,target,visual.length)));
    if(out.length<target)out.push(...general.slice(0,target-out.length));
    if(out.length<target)out.push(...rank(available.filter(item=>!out.some(value=>value.id===item.id))).slice(0,target-out.length));
    const nextSeen=[...seen,...out.map(item=>item.id)];return {items:out,seen:nextSeen,reset,remaining:Math.max(0,unique.length-nextSeen.length)};
  }
  return {CATEGORIES,SOURCES,MOTIONS,CASES,normalizedURL,duplicate,notes,caseToAesthetic,sourceToAesthetic,motionToAesthetic,caseToTopic,daily,mobileDaily,mobileBatch};
});
