const PROFILE_FIELDS=[['roles','当前身份／角色'],['background','经历与职业背景'],['strengths','擅长的创作与拍摄方式'],['works','代表作品及本人职责'],['preferences','审美偏好与不喜欢的做法'],['goals','当前目标与想发展的方向'],['constraints','时间、团队、预算及资源限制']];
function upgradeProfile(data,scopeName){if(!data.profile)data.profile={fields:Object.fromEntries(PROFILE_FIELDS.map(([k])=>[k,k==='roles'?(scopeName==='personal'?'自由创作人：导演、摄影师、个人博主':'内容总监'):''])),files:[],enabled:false};if(!data.profileImports)data.profileImports=[];if(!Array.isArray(data.inspirations))data.inspirations=[];}
function profileContext(){const p=db.profile;return {workspace:scope==='personal'?'My · 个人项目':'TMD · 工作项目',roles:scope==='personal'?'自由创作人：导演、摄影师、个人博主':'内容总监',...(p?.enabled?{confirmedProfile:p.fields,selectedDocuments:p.files.filter(f=>f.includeInAI&&f.extractedText).map(f=>({name:f.name,text:f.extractedText}))}:{})};}
function renderPersonalHome(){return hero('MY / PERSONAL WORKSPACE','导演 · 摄影师 · 个人博主','这里管理你的个人创作与其他项目，项目数量和交付形式由你决定。',btn('新建个人项目','new-project','',true)+btn('编辑我的资料','nav','data-view="profile"'))+`<div class="rule">商业拍摄、纪录片、短片、个人内容等可分别建立项目。不强制六条脚本；需要影片汇报时，再进入对应脚本的快速汇报与深化流程。</div><div class="section-head"><h2>我的项目</h2>${btn('共享审美参考','nav','data-view="aesthetic"')}</div><div class="grid">${db.projects.map(projectCard).join('')||empty('从一个个人项目开始','记录目标、你的职责、交付物、参考和执行计划。')}</div>`;}
function renderProfile(){const p=db.profile;return hero('ABOUT ME','我的资料',scope==='personal'?'My：导演、摄影师、个人博主。资料只作用于此个人空间。':'TMD：内容策划与工作职责。资料只作用于此工作空间。',btn('预览AI会使用的资料','profile-preview'))+
 `<div class="rule">资料用于提供创作背景，不是模型训练。默认只保存；开启下方开关后，勾选文档的文字和个人资料才会随生成请求发送给你配置的AI服务商。原文件不会自动发给AI，也不会自动上传GitHub。</div><div class="panel"><label><input type="checkbox" data-bool data-field="profile.enabled" ${p.enabled?'checked':''}> 生成时使用这份个人资料</label></div><div class="formgrid">${PROFILE_FIELDS.map(([k,l])=>field(l,'profile.fields.'+k,p.fields[k])).join('')}</div>
 <div class="section-head"><h2>上传简历、经历介绍或个人资料</h2>${upload('上传资料','profile-files','multiple','.txt,.md,.docx,.pdf,image/png,image/jpeg,image/webp')}</div><p class="muted">TXT／Markdown／DOCX提取文字；PDF需本机pdftotext。扫描件及图片只归档，不自动OCR，请把核对过的文字填在个人资料中。文档提取不等于AI已经阅读。旧版聊天附件未建立可靠的资料归档，请重新上传原文件。</p>
 <div class="list">${p.files.map((f,i)=>`<div class="panel"><h3>${esc(f.name)}</h3><p>${f.extractedText?`已提取 ${f.extractedText.length} 字`:'仅归档／文字尚未提取'}</p>${f.error?`<p class="missing">${esc(f.error)}</p>`:''}${f.extractionNotice?`<p class="muted">${esc(f.extractionNotice)}</p>`:''}<div class="actions"><a href="${mediaURL(f)}" target="_blank" rel="noopener">打开原文件 ↗</a>${['document','text'].includes(f.kind)?btn('本机提取文字','profile-extract',`data-index="${i}"`):''}</div>${f.extractedText?`<details><summary>查看和核对提取内容</summary>${field('文档文字（可纠正识别错误）',`profile.files.${i}.extractedText`,f.extractedText)}</details><label><input type="checkbox" data-bool data-field="profile.files.${i}.includeInAI" ${f.includeInAI?'checked':''}> 允许将此文字用于AI生成上下文</label>`:''}</div>`).join('')||empty('还没有个人资料文件','可以先直接填写上方资料，不必等上传。')}</div>
 ${db.profileImports.length?`<details class="panel"><summary>从备份恢复的个人资料副本（未自动启用）</summary><pre class="preview-copy">${esc(JSON.stringify(db.profileImports,null,2))}</pre></details>`:''}`;
}
async function profileFiles(e){if(job)throw Error('请等待当前任务结束');const files=[...e.files];const errors=[];await withJob('保存个人资料',files.length,async()=>{for(const file of files){if(stop)break;try{const f=await api('upload',file);f.name=file.name;f.includeInAI=false;db.profile.files.push(f);save();if(['.txt','.md','.docx','.pdf'].some(ext=>file.name.toLowerCase().endsWith(ext))){try{const r=await api('document/text',{localId:f.localId});f.extractedText=r.text;f.extractionNotice=r.notice;}catch(error){f.error=error.message;}save();}}catch(error){errors.push(file.name+'：'+error.message);}progress(file.name);}if(errors.length)throw Error(errors.join('；'));});}
async function profileAction(action,e){if(action==='profile-topic-report'){route={view:'topic',id:e.dataset.id,tab:'quick'};render();return;}if(action==='profile-project-topic'){const p=db.projects.find(p=>p.id===e.dataset.id);if(!isPersonalProject(p))throw Error('请选择个人项目');const t=C.topic(p.title+' · 脚本',p.id);db.topics.push(t);p.topicIds.push(t.id);save();route={view:'topic',id:t.id,tab:'quick'};render();return;}if(action==='profile-preview'){dialog('AI上下文预览',`<p class="muted">没有勾选的文件不会发送；关闭总开关后不发送个人字段与文件内容。</p><pre class="preview-copy">${esc(JSON.stringify(profileContext(),null,2))}</pre>`);return;}if(action==='profile-extract'){const f=db.profile.files[Number(e.dataset.index)];await withJob('本机提取文档文字',1,async()=>{try{const r=await api('document/text',{localId:f.localId});f.extractedText=r.text;f.extractionNotice=r.notice;f.includeInAI=false;f.error='';save();progress('已提取，请核对后勾选是否用于AI');}catch(error){f.error=error.message;save();throw error;}});}}
function isPersonalProject(p){return p?.kind==='personal';}
async function applyProfileSeed(){if(db.profile.seedImported)return;const target=db,targetScope=scope;try{const r=await api('profile-seed?scope='+encodeURIComponent(scope),undefined,{timeout:5000});if(scope!==targetScope||db!==target||!r.fields||!Object.keys(r.fields).length)return;for(const[k]of PROFILE_FIELDS)if(!db.profile.fields[k])db.profile.fields[k]=r.fields[k]||'';db.profile.seedImported=true;save();if(route.view==='profile')render();}catch{/* Static preview keeps editable fields; no false migration claim. */}}
function personalTopicCard(t){return `<article class="card"><span class="badge">${esc(t.form||'自由选题')} · ${C.quickStatus(t).ready?'汇报已齐备':'创作积累'}</span><h3>${esc(t.title)}</h3><p>${esc((t.idea||'一个尚待展开的想法').slice(0,180))}</p><div class="actions">${btn('打开选题','topic',`data-id="${t.id}"`,true)}${btn('进入汇报制作','profile-topic-report',`data-id="${t.id}"`)}</div></article>`;}
function renderPersonalIdea(t){const path='topics.'+ts(t);return hero('FREE CREATOR / IDEAS',t.title,'允许想法先不完整。记录你被什么打动、想表达什么、还想尝试什么。',btn('进入快速汇报','profile-topic-report',`data-id="${t.id}"`)+btn('深入优化','deep',`data-id="${t.id}"`))+
 `<div class="formgrid"><label>选题名称<input data-field="${path}.title" value="${esc(t.title)}"></label><label>可能的形式（可自定义）<input data-field="${path}.form" value="${esc(t.form||'')}" placeholder="电影／短片／纪录片／TVC／博主内容／AI实验"></label>${field('原始灵感与想表达的东西',path+'.idea',t.idea,true)}${field('创作母题／人物／情绪',path+'.motif',t.motif||'',true)}${field('参考来源与被触动的细节',path+'.inspirationSource',t.inspirationSource||'',true)}${field('新的尝试、问题与下一步',path+'.exploration',t.exploration||'',true)}</div><div class="panel"><h2>关联个人项目</h2><select data-topic-project="${t.id}"><option value="">暂不关联，保留为独立想法</option>${db.projects.map(p=>`<option value="${p.id}" ${t.projectId===p.id?'selected':''}>${esc(p.title)}</option>`).join('')}</select></div><div class="actions">${btn('看看审美参考','nav','data-view="aesthetic"')}${btn('查看我的资料','nav','data-view="profile"')}</div>`;}
function personalProjectCard(p){return `<article class="card"><span class="badge">个人项目 · ${esc(p.projectType||'其他')}</span><h3>${esc(p.title)}</h3><p>${esc(p.idea||'独立管理的个人创作')}</p><p>${esc(p.date||'日期待定')} · ${p.topicIds.length}条关联脚本</p>${btn('进入项目','project',`data-id="${p.id}"`,true)}</article>`;}
function renderPersonalProject(p){const path='projects.'+ps(p);return hero('PERSONAL PROJECT',p.title,'个人项目独立管理，不强制六条脚本。按项目实际产出选择策划与深化。',btn('关联已有脚本','link-topics',`data-id="${p.id}"`))+
 `<div class="formgrid"><label>项目名称<input data-field="${path}.title" value="${esc(p.title)}"></label><label>项目类型<select data-field="${path}.projectType">${['商业广告','纪录片','剧情短片','个人博主内容','其他'].map(x=>`<option ${p.projectType===x?'selected':''}>${x}</option>`).join('')}</select></label><label>目标日期<input type="date" data-field="${path}.date" value="${esc(p.date)}"></label>${field('项目目标、受众与创作想法',path+'.idea',p.idea,true)}${field('我的职责与合作分工',path+'.personalRole',p.personalRole||'自由创作人：导演、摄影师、个人博主',true)}${field('交付物与项目计划',path+'.deliverables',p.deliverables||'',true)}${field('执行记录与待办',path+'.executionNotes',p.executionNotes||'',true)}</div><div class="section-head"><h2>关联脚本</h2>${btn('为此项目新建脚本','profile-project-topic',`data-id="${p.id}"`,true)}</div><div class="grid">${p.topicIds.map(id=>db.topics.find(t=>t.id===id)).filter(Boolean).map(topicCard).join('')}</div><div class="panel"><h2>参考资料</h2><p>在审美库选用本项目，或添加本项目的场景／服装资料。</p>${btn('添加项目资料','new-asset',`data-project="${p.id}"`)}<div class="grid" style="margin-top:16px">${db.assets.filter(a=>a.projectId===p.id).map(assetCard).join('')}</div></div>`;}
