/* Lance content studio. All generation is explicit and all media stays durable. */
'use strict';
const C=StudioCore;
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=scope=>'lance_studio_v2_'+scope;
let scope=localStorage.getItem('lance_studio_scope')||'xinxuan';
let route={view:'home',id:null,tab:'quick'},db,settings,job=null,stop=false,health=null,search='';
let exportURL=null;
try{settings=JSON.parse(localStorage.getItem('lance_studio_settings')||'{}');}catch{settings={};}
settings={server:'',textModel:'',imageModel:'',videoModel:'',...settings};
let token=''; // Credentials entered here are session-only. Prefer local environment variables.
function read(scopeName){
  const stored=localStorage.getItem(key(scopeName));
  if(stored){try{const parsed=JSON.parse(stored);if(!Array.isArray(parsed.topics)||!Array.isArray(parsed.projects)||!Array.isArray(parsed.assets))throw Error();return parsed;}catch{throw Error('工作台数据无法读取，已保留原数据，请通过备份恢复。');}}
  const data={version:2,topics:[],projects:[],assets:[],exports:[],preferences:'',imported:false};
  try{
    const old=JSON.parse(localStorage.getItem('xuan_ti_ku_data_'+scopeName)||'[]');
    data.topics=old.map(C.importLegacy);
    const plans=JSON.parse(localStorage.getItem('project_plans_'+scopeName)||'[]');
    data.projects=plans.map(p=>({...C.project(p.title),id:'legacy-'+p.id,idea:p.description||p.shootTheme||'',date:p.liveDate||'',topicIds:(p.topicIds||[]).map(id=>'legacy-'+id).filter(id=>data.topics.some(t=>t.id===id))}));
    for(const p of data.projects)for(const id of p.topicIds)data.topics.find(t=>t.id===id).projectId=p.id;
    for(const oldTopic of old){const t=data.topics.find(t=>t.legacyId===oldTopic.id);if(t&&!t.projectId&&oldTopic.session){let p=data.projects.find(p=>p.title===oldTopic.session);if(!p){p=C.project(oldTopic.session);p.date=oldTopic.sessionDate||'';data.projects.push(p);}p.topicIds.push(t.id);t.projectId=p.id;}}
    data.imported=old.length>0;
  }catch(error){console.warn('Legacy data remains untouched',error.message);}
  return data;
}
function save(){
  try{const prior=localStorage.getItem(key(scope));if(prior)localStorage.setItem(key(scope)+'_previous',prior);localStorage.setItem(key(scope),JSON.stringify(db));$('.save-state')?.replaceChildren(document.createTextNode('已保存到本机 · '+new Date().toLocaleTimeString('zh-CN')));}
  catch{throw Error('本地存储空间不足，内容仍在当前页面，请立即导出备份。');}
}
function notify(message){const n=$('#notification');n.textContent=message;n.style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>n.style.display='none',6500);}
const btn=(label,action,extra='',primary=false)=>{const cls=extra.match(/class="([^"]*)"/)?.[1]||'';return `<button class="${primary?'primary ':''}${cls}" data-action="${action}" ${extra.replace(/class="[^"]*"/,'')}>${label}</button>`;};
const upload=(label,action,extra='',accept='image/*')=>`<label class="upload">${label}<input type="file" data-upload="${action}" ${extra} accept="${accept}"></label>`;
const field=(label,path,value,wide=false,short=false)=>`<label class="${wide?'wide':''}">${label}<textarea data-field="${esc(path)}" class="${short?'short':''}">${esc(value)}</textarea></label>`;
const mediaURL=a=>(settings.server||'').replace(/\/$/,'')+'/media/'+encodeURIComponent(a.localId);
const currentTopic=()=>db.topics.find(t=>t.id===route.id);
const currentProject=()=>db.projects.find(p=>p.id===route.id);
const ts=t=>db.topics.indexOf(t);
const ps=p=>db.projects.indexOf(p);
function get(path){return path.split('.').reduce((v,k)=>v?.[k],db);}
function set(path,value){const bits=path.split('.');const leaf=bits.pop();const parent=bits.reduce((v,k)=>v[k],db);parent[leaf]=value;}
function context(t){const p=db.projects.find(p=>p.id===t.projectId);const refs=db.assets.filter(a=>a.projectId===t.projectId&&t.projectId);return {project:p?{title:p.title,fields:p.fields,idea:p.idea}:null,title:t.title,idea:t.idea,quick:t.quick.fields,approved:t.quick.approved,preferences:db.preferences,assets:refs.map(a=>({name:a.name,kind:a.kind,dimensions:a.dimensions,dimensionsConfirmed:a.dimensionsConfirmed,requirements:a.requirements,analysis:a.analysis,selectedOutfits:a.outfits?.filter(o=>o.selected)})),format:'4:3 Open Gate，构图兼顾中央9:16主输出和16:9保底。尺寸不明处必须列为待确认。'};}
function referenceIDs(t){return db.assets.filter(a=>a.projectId===t.projectId&&t.projectId).flatMap(a=>[C.selected(a.proposal),...(a.outfits||[]).filter(o=>o.selected).map(o=>a.frames?.[o.frameIndex])]).filter(a=>C.assetOK(a,'image')).map(a=>a.localId).slice(0,4);}
function render(){
  const nav=[['home','工作台'],['topics','脚本与汇报'],['projects','专场排期'],['scenes','场景库'],['wardrobe','服装库'],['aesthetic','审美参考'],['archive','成果与备份']];
  $('#app').innerHTML=`<div class="shell"><aside class="side"><div class="brand">LANCE<small>CONTENT STUDIO / 内容工作台</small></div><select id="scope" aria-label="身份空间"><option value="xinxuan" ${scope==='xinxuan'?'selected':''}>TMD · 工作</option><option value="personal" ${scope==='personal'?'selected':''}>My · 个人</option></select><nav>${nav.map(([id,label])=>btn(label,'nav',`data-view="${id}" class="${route.view===id?'active':''}"`)).join('')}</nav><footer>个人创意资产<br>本机保存 · 可导出完整备份<br><a href="legacy.html" target="_blank" rel="noopener">打开旧版存档 ↗</a></footer></aside><main class="main"><div class="topbar"><span>${scope==='xinxuan'?'TMD 内容策划':'My 个人创作'} / ${nav.find(n=>n[0]===route.view)?.[1]||'项目工程'}</span><div class="actions"><span class="save-state">本机自动保存</span>${btn(health?.ok?'生成服务已连接':'连接设置','settings')}</div></div>${job?`<div class="job" role="status"><strong>${esc(job.title)}</strong><progress value="${job.done}" max="${job.total}"></progress><div class="actions"><span>${job.done}/${job.total} · ${esc(job.detail||'')}</span>${btn(stop?'正在停止…':'停止后续生成','stop')}</div></div>`:''}<div id="view">${renderView()}</div></main></div>`;
}
function hero(kicker,title,subtitle,actions=''){return `<div class="hero"><div><div class="eyebrow">${kicker}</div><h1>${esc(title)}</h1><p class="muted">${subtitle}</p></div><div class="actions">${actions}</div></div>`;}
function empty(title,body,action=''){return `<div class="empty"><h2>${title}</h2><p>${body}</p>${action}</div>`;}
function topicCard(t){const s=C.quickStatus(t),d=C.deepStatus(t);return `<article class="card"><span class="badge ${s.ready?'':'bad'}">${s.ready?'快速汇报齐备':'快速汇报缺项'}</span><h3>${esc(t.title)}</h3><p>${esc((t.idea||t.quick.fields.outline||'从一句想法开始').slice(0,150))}</p><div class="progress"><div style="width:${s.percent}%"></div></div><p>${s.images}/${t.quick.images.length}张图　${s.videos}/3段8秒视频</p><div class="actions">${btn('快速汇报','topic',`data-id="${t.id}"`,true)}${btn(`深入优化 · ${d.images}/25图`,'deep',`data-id="${t.id}"`)}</div></article>`;}
function projectCard(p){const s=C.sessionStatus(p,db.topics);return `<article class="card"><span class="badge ${s.ready?'':'bad'}">${s.ready?'专场汇报齐备':'专场待完善'}</span><h3>${esc(p.title)}</h3><p>${esc(p.date||'日期待定')} · ${s.items.length}/6条故事脚本</p><p>${s.images}张视觉参考　${s.videos}/18段8秒视频</p>${btn('进入专场','project',`data-id="${p.id}"`,true)}</article>`;}
function renderView(){
  if(route.view==='home')return hero('YOUR CREATIVE WORKSPACE','让一个想法，成为一场作品。','快速汇报与深入优化，共用同一份创意和项目资料。',btn('新建单条脚本','new-topic','',true)+btn('新建专场','new-project'))+`<div class="metrics"><div class="card"><div class="metric">${db.topics.length}</div><small>故事脚本</small></div><div class="card"><div class="metric">${db.topics.filter(t=>C.quickStatus(t).ready).length}</div><small>快速汇报齐备</small></div><div class="card"><div class="metric">${db.projects.length}</div><small>专场项目</small></div></div><div class="rule">单条：创意与脚本 + 3–5张图 + 开场／中间／结尾各8秒AI视频。<br>专场：整体方案 + 6条完整脚本，每条独立满足上述标准。</div><div class="section-head"><h2>继续创作</h2>${btn('查看所有脚本','nav','data-view="topics"')}</div><div class="grid">${db.topics.slice(0,4).map(topicCard).join('')||empty('还没有脚本','输入想法，或从旧版数据、备份开始。',btn('建立第一条脚本','new-topic','',true))}</div>`;
  if(route.view==='topics')return hero('STORIES','脚本与汇报','每条脚本拥有独立的参考素材、反馈和修改记录。',btn('新建脚本','new-topic','',true))+`<input class="workbench-search" id="search" placeholder="搜索标题或想法" value="${esc(search)}"><div class="grid" style="margin-top:20px">${db.topics.filter(t=>(t.title+t.idea).includes(search)).map(topicCard).join('')}</div>`;
  if(route.view==='projects')return hero('SESSION PLANNING','专场排期','整体方向与6条故事脚本，放在同一份汇报里。',btn('新建专场','new-project','',true))+`<div class="grid">${db.projects.map(projectCard).join('')||empty('创建一个专场','先确定创意方向和排期，再规划6条故事。')}</div>`;
  if(route.view==='topic')return renderTopic(currentTopic());
  if(route.view==='project')return renderProject(currentProject());
  if(['scenes','wardrobe','aesthetic'].includes(route.view))return renderLibrary();
  if(route.view==='asset')return renderAsset(db.assets.find(a=>a.id===route.id));
  if(route.view==='archive')return renderArchive();
  return '';
}
function readiness(s){return `<div class="rule"><strong>${s.ready?'交付内容已齐备':'尚未达到交付标准'}</strong>${s.missing.length?`<p class="missing" style="margin:8px 0 0">待补充：${esc(s.missing.join('、'))}</p>`:''}</div>`;}
function mediaMarkup(a,guides=false){if(!a)return `<div class="empty-media">尚无素材<br><small>生成成功并核验后显示</small></div>`;if(a.kind==='image')return guides?`<div class="frame"><img src="${mediaURL(a)}" alt="分镜参考"><div class="guide-v"></div><div class="guide-h"></div></div><p class="frame-label">黄色：9:16安全框　蓝色：16:9安全框（以4:3画幅为基准）</p>`:`<img class="media" src="${mediaURL(a)}" alt="视觉参考" loading="lazy">`;if(a.kind==='video')return `<video class="media" src="${mediaURL(a)}" controls preload="metadata" playsinline></video><small>实际时长 ${Number(a.duration).toFixed(2)}秒 · ${a.source==='ai'||a.source==='ai-assembly'?'AI生成':'上传素材'}</small>`;return `<a href="${mediaURL(a)}" target="_blank" rel="noopener">打开原始资料 ↗</a>`;}
function slotCard(s,path,kind,opts={}){
  const a=C.selected(s);return `<article class="card media-card"><div class="shot-title"><h3>${esc(s.label)}</h3><small>${s.locked?'已锁定':'可打磨'}</small></div>${mediaMarkup(a,opts.guides)}<label>生成描述<textarea data-field="${path}.prompt" ${s.locked?'disabled':''}>${esc(s.prompt)}</textarea></label><div class="actions">${btn(s.task?'查询已有任务':a?'重新生成':'生成'+(kind==='image'?'参考图':'视频'),'generate-slot',`data-path="${path}" data-kind="${kind}" data-duration="${opts.duration||8}" ${s.locked?'disabled':''}`,true)}${upload('上传'+(kind==='image'?(path.includes('.deep.')?'AI分镜图':'图片'):'AI视频'),'slot',`data-path="${path}" data-kind="${kind}" data-duration="${opts.duration||8}" ${s.locked?'disabled':''}`,kind==='image'?'image/png,image/jpeg,image/webp':'video/mp4,video/quicktime,video/webm')}${btn(s.locked?'解锁':'锁定','lock',`data-path="${path}"`)}</div>${s.error?`<p class="missing">${esc(s.error)}</p>`:''}${s.versions.length?`<label>历史版本（切换可对比画面与生成描述）<select data-version="${path}" ${s.locked?'disabled':''}>${s.versions.map((v,i)=>`<option value="${v.id}" ${s.selectedId===v.id?'selected':''}>第${i+1}版 · ${esc(v.createdAt.slice(0,16))}</option>`).join('')}</select></label><details><summary>查看所选版本的生成描述</summary><p class="preview-copy">${esc(a?.prompt||'上传参考')}</p></details>`:''}</article>`;
}
function renderTopic(t){if(!t)return empty('脚本不存在','请返回脚本列表。');const i=ts(t),path=`topics.${i}`;const quick=route.tab!=='deep';const s=quick?C.quickStatus(t):C.deepStatus(t);return hero(quick?'QUICK REPORT':'DEVELOPMENT',t.title,quick?'3–5张视觉参考，3段8秒AI视频，缺一不可。':'25镜逐张打磨，再生成完整AI成片参考。',btn('预览汇报','preview-topic',`data-id="${t.id}"`)+btn('下载PPT','export-topic',`data-id="${t.id}"`,true))+`<div class="tabs">${btn('快速汇报','topic',`data-id="${t.id}" ${quick?'class="active"':''}`)}${btn('深入优化','deep',`data-id="${t.id}" ${!quick?'class="active"':''}`)}</div>${readiness(s)}<div class="panel"><label>脚本名称<input data-field="${path}.title" value="${esc(t.title)}"></label><label style="margin-top:14px">原始想法与本轮修改要求<textarea data-field="${path}.idea">${esc(t.idea)}</textarea></label><label>所属专场<select data-topic-project="${t.id}"><option value="">独立脚本</option>${db.projects.map(p=>`<option value="${p.id}" ${p.id===t.projectId?'selected':''}>${esc(p.title)}</option>`).join('')}</select></label></div>${quick?renderQuick(t,path):renderDeep(t,path)}<div class="panel"><h2>汇报反馈与版本</h2><div class="actions">${btn('记录反馈／保存版本','feedback',`data-id="${t.id}"`)}${btn('确认汇报方向，进入深化','approve',`data-id="${t.id}" ${!C.quickStatus(t).ready?'disabled':''}`)}</div>${t.quick.approved?`<p class="muted">方向确认于 ${esc(t.quick.approved.time)}。深化生成以此快照为依据；修改快速稿不会覆盖已确认版本。</p>`:''}<div class="list">${t.feedback.slice().reverse().map(f=>`<div class="row"><span>${esc(f.text)}</span><small>${esc(f.time.slice(0,16))}</small></div>`).join('')}${t.snapshots.slice().reverse().map(v=>`<div class="row"><span>${esc(v.note)} · ${esc(v.time.slice(0,16))}</span>${btn('查看快照','snapshot',`data-id="${t.id}" data-snapshot="${v.id}"`)}</div>`).join('')}</div></div>`;}
function renderQuick(t,path){return `<div class="section-head"><h2>创意与故事脚本</h2><div class="actions">${btn('AI补全缺项','quick-text',`data-id="${t.id}"`)}${btn('生成全部缺失素材','quick-all',`data-id="${t.id}"`,true)}</div></div><div class="formgrid">${C.QUICK.map(([k,label])=>field(label,path+'.quick.fields.'+k,t.quick.fields[k],k==='script')).join('')}</div><div class="section-head"><h2>视觉参考 · ${t.quick.images.length}张</h2><div class="actions">${btn('增加一张','add-image',`data-id="${t.id}" ${t.quick.images.length>=5?'disabled':''}`)}${btn('移走末张到版本记录','remove-image',`data-id="${t.id}" ${t.quick.images.length<=3?'disabled':''}`)}</div></div><div class="grid">${t.quick.images.map((s,i)=>slotCard(s,`${path}.quick.images.${i}`,'image')).join('')}</div><div class="section-head"><h2>AI视频参考 · 8秒 × 3</h2></div><div class="grid">${C.PHASES.map(([k])=>slotCard(t.quick.videos[k],`${path}.quick.videos.${k}`,'video')).join('')}</div>`;}
function renderDeep(t,path){return `<div class="callout">深化以已确认的汇报方向为准。AI参考采用4:3画幅，最终摄影仍需根据实际传感器画幅核对安全框。</div><div class="section-head"><h2>执行方案</h2>${btn('AI补全执行方案','deep-fields',`data-id="${t.id}"`)}</div><div class="formgrid">${C.DEEP.map(([k,label])=>field(label,path+'.deep.fields.'+k,t.deep.fields[k])).join('')}</div><div class="section-head"><h2>25镜工程</h2><div class="actions">${btn(t.deep.shots.length?'保留旧版并重拆25镜':'AI拆解25镜','deep-shots',`data-id="${t.id}"`)}${btn('补齐25张AI图','deep-images',`data-id="${t.id}"`,true)}${btn('补齐分镜视频','deep-videos',`data-id="${t.id}"`)}</div></div>${t.deep.shots.length?`<div class="list">${t.deep.shots.map((s,j)=>`<details class="panel" ${j===0?'open':''}><summary><strong>镜 ${String(j+1).padStart(2,'0')}</strong> · ${s.duration}秒 · ${esc(s.visual.slice(0,75))}</summary><div class="formgrid">${field('画面',`${path}.deep.shots.${j}.visual`,s.visual)}${field('台词与声音',`${path}.deep.shots.${j}.dialogue`,s.dialogue)}${field('景别、运镜、灯光',`${path}.deep.shots.${j}.camera`,s.camera)}<label>时长（2–12秒）<input type="number" min="2" max="12" data-number data-field="${path}.deep.shots.${j}.duration" value="${s.duration}"></label></div><div class="grid" style="margin-top:16px">${slotCard(s.image,`${path}.deep.shots.${j}.image`,'image',{guides:true})}${slotCard(s.video,`${path}.deep.shots.${j}.video`,'video',{duration:s.duration})}</div></details>`).join('')}</div>`:empty('等待拆解分镜','先确认汇报方向，再形成完整的25镜工程。')}<div class="panel"><h2>完整AI成片参考</h2><p class="muted">按25镜顺序和脚本时长合成，保留镜头声音，可叠加你上传的配乐。剪辑节奏、口型和造型连续性仍需要逐镜审片。</p><div class="actions">${btn('合成完整AI成片','assemble',`data-id="${t.id}"`,true)}${upload('上传成片配乐','bgm',`data-id="${t.id}"`,'audio/*')}</div>${t.deep.bgm?`<p>已配置配乐：${esc(t.deep.bgm.name||'音频')}</p>`:''}${t.deep.film?mediaMarkup(t.deep.film)+`<a href="${mediaURL(t.deep.film)}" download="${esc(t.title)}_AI成片.mp4">下载完整AI成片 ↧</a>`:''}</div>`;}
function renderProject(p){if(!p)return empty('专场不存在','请返回专场列表。');const path=`projects.${ps(p)}`,s=C.sessionStatus(p,db.topics);return hero('SESSION REPORT',p.title,'整体创意 + 6条故事脚本 + 18–30张图 + 18段8秒AI视频。',btn('预览整体汇报','preview-project',`data-id="${p.id}"`)+btn('下载专场PPT','export-project',`data-id="${p.id}"`,true))+readiness(s)+`<div class="panel"><div class="formgrid"><label>专场名称<input data-field="${path}.title" value="${esc(p.title)}"></label><label>直播日期<input type="date" data-field="${path}.date" value="${esc(p.date)}"></label>${field('专场目标、受众、主题与内容组合要求',path+'.idea',p.idea,true)}</div></div><div class="section-head"><h2>整体汇报内容</h2>${btn('AI补全整体创意并规划6条脚本','project-text',`data-id="${p.id}"`,true)}</div><div class="formgrid">${C.SESSION.map(([k,label])=>field(label,path+'.fields.'+k,p.fields[k])).join('')}</div><div class="section-head"><h2>6条故事脚本</h2><div class="actions">${btn('关联已有脚本','link-topics',`data-id="${p.id}"`)}${btn('补齐6条脚本的快速素材','project-all',`data-id="${p.id}"`,true)}</div></div><div class="grid">${s.items.map(topicCard).join('')}</div><div class="section-head"><h2>本专场场景与服装</h2>${btn('上传项目资料','new-asset',`data-project="${p.id}"`)}</div><div class="grid">${db.assets.filter(a=>a.projectId===p.id).map(assetCard).join('')||empty('还没有项目资料','上传场地尺寸图、实景或过往视频，帮助生成更贴近实际的方案。')}</div>`;}
function assetCard(a){return `<article class="card"><span class="badge">${a.kind==='scene'?'场景':a.kind==='wardrobe'?'服装':'审美参考'} · ${esc(a.category||'未分类')}</span><h3>${esc(a.name)}</h3><p>${esc(a.requirements||'上传参考，积累个人审美')}</p>${btn('查看与打磨','asset',`data-id="${a.id}"`)}</article>`;}
function globalAssets(){try{return JSON.parse(localStorage.getItem('lance_studio_aesthetic')||'[]');}catch{return [];}}
function renderLibrary(){const kind={scenes:'scene',wardrobe:'wardrobe',aesthetic:'aesthetic'}[route.view];const title={scene:'场景库',wardrobe:'服装库',aesthetic:'审美参考库'}[kind];const assets=kind==='aesthetic'?globalAssets():db.assets.filter(a=>a.kind===kind);return hero('CREATIVE ASSETS',title,kind==='scene'?'真实场地尺寸、已有参考与AI布景方案。':kind==='wardrobe'?'过往视频归档、造型提取和项目搭配推荐。':'TMD与My共享你的审美积累。',btn('建立资料专题','new-asset',`data-kind="${kind}"`,true))+`<div class="grid">${assets.map(a=>assetCard(a).replace('data-action="asset"','data-action="'+(kind==='aesthetic'?'global-asset':'asset')+'"')).join('')||empty('建立第一个专题','可以先创建资料卡，再上传图片、尺寸图和视频。')}</div>`;}
function renderAsset(a){if(!a)return empty('资料不存在','返回资料库继续。');const path='assets.'+db.assets.indexOf(a);const p=db.projects.find(p=>p.id===a.projectId);return hero('PROJECT REFERENCES',a.name,`${esc(a.category||'未分类')} · ${esc(p?.title||'未关联专场')}`,btn('返回资料库','nav',`data-view="${a.kind==='scene'?'scenes':'wardrobe'}"`))+`<div class="panel"><div class="formgrid"><label>专题名称<input data-field="${path}.name" value="${esc(a.name)}"></label><label>分类／标签<input data-field="${path}.category" value="${esc(a.category)}"></label><label>所属专场<select data-field="${path}.projectId"><option value="">不关联</option>${db.projects.map(p=>`<option value="${p.id}" ${p.id===a.projectId?'selected':''}>${esc(p.title)}</option>`).join('')}</select></label>${field('想要的场景／搭配效果、参考重点',path+'.requirements',a.requirements,true)}${a.kind==='scene'?field('场地尺寸、层高、柱位、出入口、电源与搭建限制',path+'.dimensions',a.dimensions,true)+`<label><input type="checkbox" data-bool data-field="${path}.dimensionsConfirmed" ${a.dimensionsConfirmed?'checked':''}> 我已核对以上尺寸，图上不清楚的部分已标注</label>`:field('服装库存、尺码、存放位置、采购／租赁条件',path+'.inventory',a.inventory,true)}</div></div><div class="section-head"><h2>原始资料</h2>${upload('上传尺寸图／参考／视频','asset',`data-id="${a.id}"`,'image/png,image/jpeg,image/webp,video/mp4,video/quicktime,video/webm,application/pdf')}</div><p class="muted">单文件最多250MB。PDF可归档；AI识图请另外上传清晰的尺寸图截图。</p><div class="grid">${a.files.map((f,i)=>`<div class="card media-card">${mediaMarkup(f)}<small>${esc(f.name)}</small>${f.kind==='video'?btn('提取12个候选关键帧','frames',`data-id="${a.id}" data-file="${i}"`):''}</div>`).join('')}</div><div class="section-head"><h2>${a.kind==='scene'?'场地分析与可落地方案':'造型识别与搭配建议'}</h2><div class="actions">${btn(a.kind==='scene'?'AI分析场地与参考':'AI识别关键帧服装','analyze-asset',`data-id="${a.id}"`,true)}</div></div><div class="panel">${field('分析与执行建议（可修改，未核实内容须保留标注）',path+'.analysis',a.analysis)}${a.kind==='wardrobe'?`<p class="muted">关键帧采用均匀采样，可能遗漏换装瞬间。可追加视频或上传你截取的清晰画面。</p><div class="grid">${(a.outfits||[]).map((o,i)=>`<div class="card">${mediaMarkup(a.frames[o.frameIndex])}<h3>${esc(o.name)}</h3><p>${esc(o.description)}</p><p>${esc(o.recommendation)}</p><p class="muted">来源时间点：${a.frames[o.frameIndex]?.timestamp??'手动上传'}秒</p><label><input type="checkbox" data-bool data-field="${path}.outfits.${i}.selected" ${o.selected?'checked':''}> 选为本项目造型依据</label></div>`).join('')}</div>`:''}</div><div class="section-head"><h2>${a.kind==='scene'?'场景效果参考':'搭配效果参考'}</h2></div>${slotCard(a.proposal,path+'.proposal','image')}<p class="muted">原图与AI效果分别保存。场景效果图用于沟通，未经现场核实不能作为施工图。</p>`;}
function renderArchive(){return hero('DELIVERABLES','成果与备份','PPT和素材保存在生成成果中，可重复下载。备份包包含当前空间和共享审美资料。',btn('导出完整备份ZIP','backup','',true)+upload('导入备份（新空间副本）','restore','','application/zip'))+`<div class="panel">${field('我的审美与创作偏好（生成时会读取，可随时纠正）','preferences',db.preferences)}<p class="muted">系统使用你明确保存的偏好、已选造型和汇报反馈作为生成依据，目前不声称自动训练或自主学习。</p></div><div class="list">${db.exports.slice().reverse().map(e=>`<div class="card"><h3>${esc(e.title)}</h3><p>${esc(e.time)} · ${e.kind==='project'?'专场':'单条'} · 已生成PPT文件</p>${btn('重新下载','redownload',`data-id="${e.id}"`)}</div>`).join('')||empty('还没有可下载成果','素材齐备后，在脚本或专场内下载PPT。未齐备时可以预览缺项。')}</div>`;}
function dialog(title,body,actions=''){const d=$('#dialog');$('#dialog-content').innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2>${btn('关闭','close')}</div>${body}<div class="actions" style="margin-top:20px">${actions}</div>`;if(!d.open)d.showModal();}
function close(){if($('#dialog').open)$('#dialog').close();}
async function api(path,body,options={}){
  const headers={...(body instanceof File?{'X-File-Name':encodeURIComponent(body.name)}:{'Content-Type':'application/json'})};if(token)headers.Authorization='Bearer '+token;
  let response;try{response=await fetch((settings.server||'').replace(/\/$/,'')+'/api/'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:body instanceof File?body:JSON.stringify(body),signal:AbortSignal.timeout(options.timeout||300000)});}catch(error){throw Error(error.name==='TimeoutError'?'请求超时，已保留成果。视频任务可继续查询。':'生成服务未连接。请运行 python3 studio_server.py，并从 http://127.0.0.1:8000 打开。');}
  let result;try{result=await response.json();}catch{throw Error('当前地址只提供静态页面，请启动内容工作台服务后重试');}
  if(!response.ok||result.error&& !result.status)throw Error(result.error||'服务请求失败');return result;
}
async function chat(prompt,refs=[]){const r=await api('chat',{model:settings.textModel,prompt,references:refs});return C.parseJSON(r.text);}
async function delay(ms){await new Promise(r=>setTimeout(r,ms));}
async function pollJob(id){for(let n=0;n<600;n++){const r=await api('jobs/'+id);if(r.status==='succeeded')return r.result;if(r.status==='failed')throw Error(r.error);await delay(2000);}throw Error('处理超时，请稍后检查成果。');}
async function withJob(title,total,fn){if(job){notify('当前任务仍在运行，请等待或停止后续生成。');return;}job={title,done:0,total,detail:''};stop=false;render();try{await fn();if(!stop)notify('本轮处理结束，是否齐备以缺项检查为准。');}catch(error){notify(error.message);}finally{job=null;save();render();}}
function progress(detail){if(!job)return;job.detail=detail;job.done++;save();render();}
async function ensureService(){health=await api('health');if(!health.ffmpeg)throw Error('缺少FFmpeg，无法验证视频时长和保存媒体，请先安装后重试。');}
function quickPrompt(t){return `根据以下资料补全单条快速汇报。遵守已确认方向，不统一套用史诗风格。脚本应有完整起承转合与台词，所有产品性能、人物事实必须有依据或标为待确认。参考图与视频用于汇报，不以文字代替最终媒体。\n${JSON.stringify(context(t))}\n只返回JSON：{"fields":${JSON.stringify(Object.fromEntries(C.QUICK.map(([k,l])=>[k,l])))},"imagePrompts":[恰好${t.quick.images.length}条详细视觉描述],"videoPrompts":{"opening":"开场独立8秒，明确镜头、动作、声音和节奏","middle":"中间独立8秒","ending":"结尾独立8秒"}}` ;}
async function generateQuickText(t){const parsed=C.validateQuick(await chat(quickPrompt(t),referenceIDs(t)),t.quick.images.length);C.snapshot(t,'AI补全前的快速汇报');for(const[k]of C.QUICK)if(!C.text(t.quick.fields[k]))t.quick.fields[k]=parsed.fields[k];t.quick.images.forEach((s,i)=>{if(!s.locked&&!C.text(s.prompt))s.prompt=parsed.imagePrompts[i];});for(const[k]of C.PHASES)if(!t.quick.videos[k].locked&&!C.text(t.quick.videos[k].prompt))t.quick.videos[k].prompt=parsed.videoPrompts[k];save();}
function ownerOf(path){return path.startsWith('topics.')?db.topics[Number(path.split('.')[1])]:null;}
function refreshReadiness(){const target=$('#view > .rule');const t=currentTopic(),p=currentProject();if(target&&(t||p))target.outerHTML=readiness(t?(route.tab==='deep'?C.deepStatus(t):C.quickStatus(t)):C.sessionStatus(p,db.topics));const approve=$('[data-action="approve"]');if(approve&&t)approve.disabled=!C.quickStatus(t).ready;}
function deepPreviewHTML(t){return readiness(C.deepStatus(t))+C.DEEP.map(([k,l])=>`<div class="preview-block"><h2>${l}</h2><p class="preview-copy">${esc(t.deep.fields[k]||'待补充')}</p></div>`).join('')+t.deep.shots.map((s,i)=>`<div class="preview-block"><h2>镜 ${i+1} · ${s.duration}秒</h2><p>${esc(s.visual)}</p><p>${esc(s.dialogue)}</p><p>${esc(s.camera)}</p>${mediaMarkup(C.selected(s.image),true)}</div>`).join('')+`<h2>完整AI成片参考</h2>${mediaMarkup(t.deep.film)}`;}
async function generateSlot(path,kind,duration=8){
  const slot=get(path);if(slot.locked)throw Error('参考已锁定，请先解锁');if(!C.text(slot.prompt))throw Error('请先填写该素材的生成描述');const t=ownerOf(path);const asset=path.startsWith('assets.')?db.assets[Number(path.split('.')[1])]:null;
  const refs=asset?[...asset.files.filter(f=>f.kind==='image'),...(asset.frames||[]).filter((_,i)=>(asset.outfits||[]).some(o=>o.selected&&o.frameIndex===i))].map(f=>f.localId).slice(0,4):t?referenceIDs(t):[];
  const prompt=slot.prompt+'\n保持同一人物、产品、服装与场景。'+(t?'项目资料：'+JSON.stringify(context(t)):'场地或服装资料：'+JSON.stringify({dimensions:asset?.dimensions,dimensionsConfirmed:asset?.dimensionsConfirmed,analysis:asset?.analysis,requirements:asset?.requirements}));
  try{
    let result;
    if(kind==='image'){const prior=C.selected(slot);const editRefs=[...(C.assetOK(prior,'image')?[prior.localId]:[]),...refs];result=await api('image',{model:settings.imageModel,prompt:prompt+(prior?'\n第一张参考是当前版本，请按本轮描述修改，并保留没有要求变化的主体与空间关系。':''),references:[...new Set(editRefs)].slice(0,4)});}
    else{
      let reference=null;
      if(path.includes('.deep.shots.')){const shot=t.deep.shots[Number(path.split('.')[4])];reference=C.selected(shot.image)?.localId;}
      else if(t){const k=path.split('.').at(-1);const index={opening:0,middle:1,ending:t.quick.images.length-1}[k];reference=C.selected(t.quick.images[index])?.localId;}
      if(!reference)throw Error('请先生成或上传对应参考图，再生成视频以保持造型一致');
      if(!slot.task){const submission=await api('video',{model:settings.videoModel,prompt,reference,duration,ratio:'4:3'});slot.task={id:submission.taskId,duration,startedAt:new Date().toISOString()};save();}
      for(let attempt=0;attempt<450;attempt++){
        if(stop){slot.error='查询已暂停，任务ID已保存。再次点击将继续查询，不重复提交。';save();return;}
        const status=await api('video/status',{taskId:slot.task.id});
        if(status.status==='succeeded'){result=status.asset;break;}
        if(['failed','expired','cancelled'].includes(status.status)){slot.task=null;throw Error(status.error||'视频任务失败，请重试');}
        await delay(2000);
      }
      if(!result)throw Error('视频仍在排队。任务ID已保留，稍后点击继续查询。');
      if(Math.abs(result.duration-duration)>0.15){slot.task=null;throw Error(`视频实际为${result.duration.toFixed(2)}秒，不满足${duration}秒要求。请调整视频模型后重试。`);}
    }
    C.putVersion(slot,result);save(); // Keep prior film accessible; fingerprint marks it out of date.
  }catch(error){slot.error=error.message;save();throw error;}
}
async function quickAll(t){if(C.QUICK.some(([k])=>!C.text(t.quick.fields[k]))||t.quick.images.some(s=>!C.text(s.prompt))||C.PHASES.some(([k])=>!C.text(t.quick.videos[k].prompt)))await generateQuickText(t);progress('创意内容已检查');const path='topics.'+ts(t);const errors=[];for(let i=0;i<t.quick.images.length;i++){if(stop)break;const s=t.quick.images[i];if(!C.assetOK(C.selected(s),'image')){try{await generateSlot(`${path}.quick.images.${i}`,'image');}catch(e){errors.push(e.message);}}progress('参考图 '+(i+1)+'/'+t.quick.images.length);}for(const[k,label]of C.PHASES){if(stop)break;const s=t.quick.videos[k];const a=C.selected(s);if(!C.assetOK(a,'video')||Math.abs(a.duration-8)>0.15||a.source!=='ai'){try{await generateSlot(`${path}.quick.videos.${k}`,'video',8);}catch(e){errors.push(e.message);}}progress(label+'视频已处理');}if(errors.length)throw Error(`${errors.length}项未完成：${errors[0]}`);}
async function projectText(p){
  const raw=await chat(`规划一个专场整体汇报与6条不同的故事脚本。必须满足恰好6条，可结合预热和走心访谈，由实际目标决定，不得所有片套同一风格。已有脚本只作为上下文，本次不覆盖。\n项目：${JSON.stringify(p)}\n已有脚本：${JSON.stringify(p.topicIds.map(id=>db.topics.find(t=>t.id===id)).filter(Boolean).map(t=>({title:t.title,idea:t.idea})))}\n只输出JSON：{"fields":${JSON.stringify(Object.fromEntries(C.SESSION.map(([k,l])=>[k,l])))},"stories":[6个对象，每个{"title":"名称","idea":"故事创意与差异化作用"}]}`);
  const fields=C.validateFields(raw.fields,C.SESSION);if(!Array.isArray(raw.stories)||raw.stories.length!==6||raw.stories.some(s=>!C.text(s.title)||!C.text(s.idea)))throw Error('AI未给出完整6条脚本规划，原项目已保留');
  for(const[k]of C.SESSION)if(!C.text(p.fields[k]))p.fields[k]=fields[k];
  const needed=6-p.topicIds.length;if(needed<0)throw Error('专场超过6条，请先调整关联脚本');
  raw.stories.slice(0,needed).forEach(s=>{const t=C.topic(s.title,p.id);t.idea=s.idea;db.topics.push(t);p.topicIds.push(t.id);});save();
}
async function deepFields(t){if(!t.quick.approved)throw Error('请先在快速汇报中确认方向');const raw=await chat(`深化以下已确认创意。考虑真实场地约束、人物表演、预算排期和拍摄可行性。未知报价和尺寸列待确认。${JSON.stringify(context(t))}\n返回JSON：{"fields":${JSON.stringify(Object.fromEntries(C.DEEP.map(([k,l])=>[k,l])))}}`,referenceIDs(t));const fields=C.validateFields(raw.fields,C.DEEP);C.snapshot(t,'补全执行方案之前');for(const[k]of C.DEEP)if(!C.text(t.deep.fields[k]))t.deep.fields[k]=fields[k];save();}
async function deepShots(t){if(!t.quick.approved)throw Error('请先确认汇报方向');const raw=await chat(`按确认的完整故事脚本拆分恰好25镜，严格延续人物、造型、空间和情绪，镜头有可剪辑的衔接。默认4:3，兼顾9:16/16:9。每镜2–12秒整数，时长总和应符合剧本。${JSON.stringify(context(t))}\n执行方案：${JSON.stringify(t.deep.fields)}\n返回JSON：{"shots":[25个对象，每个{"visual":"具体画面","dialogue":"台词与声音，无台词时写无台词","camera":"景别、运镜、焦段、灯光","duration":3,"imagePrompt":"参考图提示词","videoPrompt":"该镜动作、运镜与声音提示词"}]}`,referenceIDs(t));const shots=C.validateShots(raw);C.snapshot(t,'重新拆分25镜之前');t.deep.shots=shots;t.deep.film=null;save();}
async function assembleFilm(t){const s=C.deepStatus(t);if(t.deep.shots.length!==25||s.images!==25||s.videos!==25)throw Error('需先补齐25张AI分镜图和25段对应AI视频');const missing=C.DEEP.filter(([k])=>!C.text(t.deep.fields[k]));if(missing.length)throw Error('请先完成执行方案：'+missing.map(([,v])=>v).join('、'));const fingerprint=C.shotFingerprint(t.deep.shots);const bgmId=t.deep.bgm?.localId||null;const clips=t.deep.shots.map(s=>({localId:C.selected(s.video).localId,duration:s.duration,ratio:'4:3'}));const submission=await api('assemble',{clips,bgm:t.deep.bgm?.localId});const film=await pollJob(submission.jobId);if(t.deep.film)C.snapshot(t,'合成新版成片之前');t.deep.film={...film,fingerprint,bgmId};save();}
function previewHTML(t){return `<div class="report-cover"><small>单条创意汇报</small><h1>${esc(t.title)}</h1></div>${readiness(C.quickStatus(t))}${C.QUICK.map(([k,label])=>`<div class="preview-block"><h2>${label}</h2><p class="preview-copy">${esc(t.quick.fields[k]||'待补充')}</p></div>`).join('')}<div class="preview-block"><h2>视觉参考</h2><div class="grid">${t.quick.images.map(s=>mediaMarkup(C.selected(s))).join('')}</div></div><div class="preview-block"><h2>开场／中间／结尾各8秒</h2>${C.PHASES.map(([k,label])=>`<h3>${label}</h3>${mediaMarkup(C.selected(t.quick.videos[k]))}`).join('')}</div>`;}
function showSettings(){dialog('生成服务与模型连接',`<p class="muted">新工作台使用方舟文本、图片和视频接口。三个模型ID须填写你账户已开通的实际模型，视频模型须支持8秒和图生视频。Key只在本次页面会话使用，也可由本地.env提供。</p><div class="formgrid"><label class="wide">工作台服务地址（本机启动时留空）<input id="cfg-server" value="${esc(settings.server)}" placeholder="http://127.0.0.1:8000"></label><label class="wide">Ark API Key<input type="password" id="cfg-token" value="" autocomplete="off" placeholder="留空使用本机环境变量或本次会话已有Key"></label>${['text','image','video'].map(k=>`<label class="wide">${{text:'文本／看图',image:'图片／参考图编辑',video:'视频／支持8秒'}[k]}模型ID<input id="cfg-${k}" value="${esc(settings[k+'Model'])}"></label>`).join('')}</div><p id="connection-result" class="muted">连接检查不调用付费模型。</p>`,btn('保存并检查连接','save-settings','',true));}
async function backup(){if(!window.JSZip)throw Error('备份组件未加载');const zip=new JSZip();zip.file('studio.json',JSON.stringify({scope,data:db,aesthetic:globalAssets()},null,2));const ids=[...new Set(JSON.stringify([db,globalAssets()]).match(/[a-f0-9]{32}\.(?:mp4|mov|webm|jpg|jpeg|png|webp|pdf|mp3|wav|m4a)/g)||[])];for(const id of ids){const response=await fetch(mediaURL({localId:id}));if(!response.ok)throw Error('备份中断：素材'+id+'无法读取，未交付不完整备份');zip.file('media/'+id,await response.blob());progress('备份素材');}downloadBlob(await zip.generateAsync({type:'blob'}),'Lance完整备份_'+scope+'.zip');}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function restore(file){const zip=await JSZip.loadAsync(file);if(!zip.file('studio.json'))throw Error('不是Lance工作台备份');const raw=JSON.parse(await zip.file('studio.json').async('string'));if(raw.data?.version!==2||!Array.isArray(raw.data.topics)||!Array.isArray(raw.data.assets))throw Error('备份格式错误');let json=JSON.stringify(raw.data);let aesthetic=JSON.stringify(raw.aesthetic||[]);for(const name of Object.keys(zip.files).filter(n=>n.startsWith('media/')&&!zip.files[n].dir)){const bytes=await zip.files[name].async('blob');const result=await api('upload',new File([bytes],name.split('/').at(-1)));const old=name.split('/').at(-1);json=json.split(old).join(result.localId);aesthetic=aesthetic.split(old).join(result.localId);progress('恢复素材');}const restored=JSON.parse(json);const suffix='（恢复副本）';const projectMap=new Map(restored.projects.map(p=>[p.id,C.uid()]));const topicMap=new Map(restored.topics.map(t=>[t.id,C.uid()]));restored.projects.forEach(p=>{p.id=projectMap.get(p.id);p.title+=suffix;p.topicIds=p.topicIds.map(id=>topicMap.get(id)).filter(Boolean);});restored.topics.forEach(t=>{t.id=topicMap.get(t.id);t.title+=suffix;t.projectId=projectMap.get(t.projectId)||null;});restored.assets.forEach(a=>{a.id=C.uid();a.name+=suffix;a.projectId=projectMap.get(a.projectId)||null;});db.projects.push(...restored.projects);db.topics.push(...restored.topics);db.assets.push(...restored.assets);const globals=globalAssets();JSON.parse(aesthetic).forEach(a=>{a.id=C.uid();a.name+=suffix;globals.push(a);});localStorage.setItem('lance_studio_aesthetic',JSON.stringify(globals));save();}
async function extractAssetFrames(a,fileIndex){const file=a.files[fileIndex];const submission=await api('frames',{localId:file.localId});const frames=await pollJob(submission.jobId);a.frames.push(...frames);save();}
async function analyzeAsset(a){const files=a.kind==='wardrobe'?a.frames:a.files.filter(f=>f.kind==='image');if(!files.length)throw Error(a.kind==='wardrobe'?'请先提取视频关键帧，或上传服装截图':'请上传清晰的尺寸图或场地照片');const refs=files.slice(-12);const prompt=a.kind==='scene'?`你是场景美术与摄影指导。读取尺寸图及参考，不编造无法辨认的尺寸。已核对尺寸：${a.dimensionsConfirmed}。尺寸：${a.dimensions}。目标：${a.requirements}。提出符合空间的布景、人物动线、机位、灯位、材料、预算估算依据与待核实限制。必须明确效果图不是施工图。返回{"analysis":"完整可编辑分析","prompt":"基于参考图的场景效果生成描述"}`:`分析这${refs.length}个视频关键帧的服装，合并重复造型。只识别可见衣服，不猜品牌、身份与看不清的材质。目标：${a.requirements}；库存条件：${a.inventory}。返回{"analysis":"整体造型与本项目推荐理由","prompt":"结合所选风格的搭配效果图描述","outfits":[{"frameIndex":0,"name":"造型名称","description":"上装/下装/配饰/色彩/廓形","recommendation":"适合的场景、人物、灯光与动作，哪些需确认"}]}`;
  const raw=await chat(prompt,refs.map(f=>f.localId));if(!C.text(raw.analysis)||!C.text(raw.prompt))throw Error('分析结果不完整，原稿已保留');a.analysis=raw.analysis;if(!a.proposal.locked)a.proposal.prompt=raw.prompt;if(a.kind==='wardrobe'){if(!Array.isArray(raw.outfits))throw Error('未识别到造型列表');a.outfits=raw.outfits.filter(o=>Number.isInteger(o.frameIndex)&&o.frameIndex>=0&&o.frameIndex<refs.length).map(o=>({...o,frameIndex:a.frames.indexOf(refs[o.frameIndex]),selected:false}));}save();}
document.addEventListener('change',async event=>{
  const e=event.target;
  try{
    if(e.id==='scope'){if(job){e.value=scope;throw Error('生成期间请先停止后续任务，再切换空间');}scope=e.value;localStorage.setItem('lance_studio_scope',scope);db=read(scope);route={view:'home'};save();render();return;}
    if(e.dataset.field){if(job)throw Error('生成过程中暂不修改，停止后可打磨');set(e.dataset.field,e.hasAttribute('data-bool')?e.checked:e.hasAttribute('data-number')?Number(e.value):e.value);save();refreshReadiness();return;}
    if(e.dataset.version){const s=get(e.dataset.version);if(s.locked)throw Error('参考已锁定');s.selectedId=e.value;s.prompt=C.selected(s)?.prompt||s.prompt;save();render();return;}
    if(e.dataset.topicProject){const t=db.topics.find(t=>t.id===e.dataset.topicProject);const p=db.projects.find(p=>p.id===e.value);if(p&&!p.topicIds.includes(t.id)&&p.topicIds.length>=6)throw Error('专场已满6条，请先调整关联');db.projects.forEach(p=>p.topicIds=p.topicIds.filter(id=>id!==t.id));t.projectId=e.value||null;if(p)p.topicIds.push(t.id);save();render();return;}
    if(e.dataset.upload){if(!e.files[0])return;const file=e.files[0];if(job)throw Error('请等当前处理完成');await withJob('上传与核验',1,async()=>{
      if(e.dataset.upload==='restore'){await restore(file);return;}
      await ensureService();const result=await api('upload',file);result.name=file.name;
      if(e.dataset.upload==='slot'){const kind=e.dataset.kind;if((kind==='video'||e.dataset.path.includes('.deep.'))&&!confirm('请确认：这份上传素材是AI生成的参考。系统会核验文件和时长，但无法鉴定它是否由AI制作。'))return;if(result.kind!==kind)throw Error('素材类型不匹配');if(kind==='video'){const duration=Number(e.dataset.duration);if(Math.abs(result.duration-duration)>0.15)throw Error(`实际${result.duration.toFixed(2)}秒，需要${duration}秒`);result.source='ai';result.provenance='用户声明为AI视频参考';}if(e.dataset.path.includes('.deep.')&&kind==='image'){result.source='ai';result.provenance='用户声明为AI分镜参考';}C.putVersion(get(e.dataset.path),result);}
      if(e.dataset.upload==='asset'){const a=db.assets.find(a=>a.id===e.dataset.id);a.files.push(result);if(a.kind==='wardrobe'&&result.kind==='image')a.frames.push(result);}
      if(e.dataset.upload==='bgm'){if(result.kind!=='audio')throw Error('请上传音频文件');db.topics.find(t=>t.id===e.dataset.id).deep.bgm=result;}
      if(e.dataset.upload==='global'){const all=globalAssets();const a=all.find(a=>a.id===e.dataset.id);a.files.push(result);localStorage.setItem('lance_studio_aesthetic',JSON.stringify(all));}
      save();progress('素材已核验并保存');
    });}
  }catch(error){notify(error.message);render();}
});
document.addEventListener('input',event=>{if(event.target.id==='search'){search=event.target.value;const pos=event.target.selectionStart;render();$('#search')?.focus();$('#search')?.setSelectionRange(pos,pos);}});
document.addEventListener('click',async event=>{
  const e=event.target.closest('[data-action]');if(!e)return;const action=e.dataset.action;const t=db.topics.find(t=>t.id===e.dataset.id);const p=db.projects.find(p=>p.id===e.dataset.id);const a=db.assets.find(a=>a.id===e.dataset.id);
  try{
    if(job&&!['stop','close','nav','topic','deep','project','asset'].includes(action))throw Error('当前任务仍在运行，请先等待或停止后续生成');
    if(action==='stop'){stop=true;render();return;}
    if(action==='close'){close();return;}
    if(action==='nav'){route={view:e.dataset.view};search='';render();return;}
    if(['topic','deep','project','asset'].includes(action)){route={view:action==='deep'?'topic':action,id:e.dataset.id,tab:action==='deep'?'deep':'quick'};render();return;}
    if(action==='new-topic'||action==='new-project'){dialog(action==='new-topic'?'建立单条脚本':'建立整体专场',`<label>名称<input id="new-title" placeholder="例如：下播后的最后一束光"></label><label style="margin-top:14px">创意想法<textarea id="new-idea" placeholder="想说什么、拍谁、给谁看、希望观众感受到什么"></textarea></label>`,btn('创建并开始','create',`data-kind="${action==='new-topic'?'topic':'project'}"`,true));return;}
    if(action==='create'){const title=$('#new-title').value.trim();if(!title)throw Error('请填写名称');const item=e.dataset.kind==='topic'?C.topic(title):C.project(title);item.idea=$('#new-idea').value;db[e.dataset.kind==='topic'?'topics':'projects'].push(item);route={view:e.dataset.kind,id:item.id,tab:'quick'};save();close();render();return;}
    if(action==='settings'){showSettings();return;}
    if(action==='save-settings'){settings.server=$('#cfg-server').value.trim().replace(/\/$/,'');if(settings.server&&!/^https?:\/\//.test(settings.server))throw Error('服务地址需要以http://或https://开头');for(const k of ['text','image','video'])settings[k+'Model']=$('#cfg-'+k).value.trim();token=$('#cfg-token').value.trim()||token;localStorage.setItem('lance_studio_settings',JSON.stringify(settings));try{health=await api('health');for(const k of ['text','image','video'])if(!settings[k+'Model'])settings[k+'Model']=health.models[k]||'';localStorage.setItem('lance_studio_settings',JSON.stringify(settings));$('#connection-result').textContent=`服务已连接；${health.ffmpeg?'媒体核验可用':'缺少FFmpeg'}；${health.keyConfigured||token?'已有Key，真实模型调用尚待验证':'尚未提供API Key'}`;}catch(err){$('#connection-result').textContent=err.message;}return;}
    if(action==='add-image'){if(t.quick.images.length>=5)return;t.quick.images.push(C.slot('补充视觉'+(t.quick.images.length+1)));save();render();return;}
    if(action==='remove-image'){if(t.quick.images.length<=3)return;C.snapshot(t,'调整参考图数量前');t.quick.images.pop();save();render();return;}
    if(action==='lock'){const s=get(e.dataset.path);if(!s.locked&&!C.selected(s))throw Error('先生成或上传参考，才能锁定');s.locked=!s.locked;save();render();return;}
    if(action==='generate-slot'){await withJob('生成单项参考',1,async()=>{await ensureService();await generateSlot(e.dataset.path,e.dataset.kind,Number(e.dataset.duration));progress('本项已处理');});return;}
    if(action==='quick-text'){await withJob('补全创意与脚本',1,async()=>{await generateQuickText(t);progress('文本已补全');});return;}
    if(action==='quick-all'){await withJob('快速汇报素材生成',1+t.quick.images.length+3,async()=>{await ensureService();await quickAll(t);});return;}
    if(action==='project-text'){await withJob('专场创意与6条脚本规划',1,async()=>{await projectText(p);progress('已保存整体方案和脚本规划');});return;}
    if(action==='project-all'){if(p.topicIds.length!==6)throw Error('先关联或生成恰好6条脚本');await withJob('专场快速汇报 · 6条故事',p.topicIds.reduce((n,id)=>n+4+db.topics.find(t=>t.id===id).quick.images.length,0),async()=>{await ensureService();const errors=[];for(const id of p.topicIds){if(stop)break;try{await quickAll(db.topics.find(t=>t.id===id));}catch(err){errors.push(err.message);}}if(errors.length)throw Error('部分脚本素材未齐备：'+errors.join('；'));});return;}
    if(action==='deep-fields'||action==='deep-shots'){await withJob(action==='deep-fields'?'完善执行方案':'拆解25镜',1,async()=>{await (action==='deep-fields'?deepFields(t):deepShots(t));progress('结果已保存');});return;}
    if(action==='deep-images'||action==='deep-videos'){if(!t.quick.approved||t.deep.shots.length!==25)throw Error('请先确认方向并拆解25镜');await withJob(action==='deep-images'?'25张AI分镜参考':'25镜AI视频',25,async()=>{await ensureService();const kind=action==='deep-images'?'image':'video';const errors=[];for(let j=0;j<25;j++){if(stop)break;const s=t.deep.shots[j],ref=C.selected(s[kind]);if(!C.assetOK(ref,kind)||ref.source!=='ai'||kind==='video'&&Math.abs(ref.duration-s.duration)>0.15){try{await generateSlot(`topics.${ts(t)}.deep.shots.${j}.${kind}`,kind,s.duration);}catch(err){errors.push(`镜${j+1}：${err.message}`);}}progress('镜'+(j+1)+'已处理');}if(errors.length)throw Error(errors.join('；'));});return;}
    if(action==='assemble'){await withJob('合成完整AI成片',1,async()=>{await ensureService();await assembleFilm(t);progress('成片已保存');});return;}
    if(action==='approve'){if(!C.quickStatus(t).ready)throw Error('快速汇报缺项，暂不能确认');C.snapshot(t,'汇报确认版');t.quick.approved={time:new Date().toISOString(),fields:C.clone(t.quick.fields),images:t.quick.images.map(C.selected),videos:C.clone(t.quick.videos),feedback:C.clone(t.feedback)};route.tab='deep';save();render();return;}
    if(action==='feedback'){dialog('记录汇报反馈',`<label>采纳的方向、需要修改的地方<textarea id="feedback-text"></textarea></label>`,btn('保存反馈和当前快照','save-feedback',`data-id="${t.id}"`,true));return;}
    if(action==='save-feedback'){const text=$('#feedback-text').value.trim();if(!text)throw Error('请填写反馈');t.feedback.push({time:new Date().toISOString(),text});C.snapshot(t,text);save();close();render();return;}
    if(action==='snapshot'){const snap=t.snapshots.find(s=>s.id===e.dataset.snapshot);dialog(snap.note,previewHTML(snap.data));return;}
    if(action==='preview-topic'){dialog(t.title,route.tab==='deep'?deepPreviewHTML(t):previewHTML(t));return;}
    if(action==='preview-project'){dialog(p.title,readiness(C.sessionStatus(p,db.topics))+C.SESSION.map(([k,l])=>`<div class="preview-block"><h2>${l}</h2><p class="preview-copy">${esc(p.fields[k]||'待补充')}</p></div>`).join('')+p.topicIds.map(id=>db.topics.find(t=>t.id===id)).filter(Boolean).map(previewHTML).join(''));return;}
    if(action==='export-topic'||action==='export-project'){await withJob('生成可编辑PPT',1,async()=>{await StudioPpt.exportReport(action==='export-topic'?t:p,action==='export-topic'?(route.tab==='deep'?'deep':'topic'):'project',{db,mediaURL,api,downloadBlob,progress,save});});return;}
    if(action==='redownload'){const record=db.exports.find(x=>x.id===e.dataset.id);const blob=await StudioPpt.getExport(record.id);if(!blob)throw Error('本机成果文件不存在，可从对应脚本重新导出');downloadBlob(blob,record.title+'.pptx');return;}
    if(action==='link-topics'){dialog('选择本专场的6条脚本',`<p class="muted">已关联其他专场的脚本不在此处移动。可在单条脚本里调整所属专场。</p>${db.topics.filter(t=>!t.projectId||t.projectId===p.id).map(t=>`<label class="file-row"><input type="checkbox" name="topic-link" value="${t.id}" ${p.topicIds.includes(t.id)?'checked':''}> ${esc(t.title)}</label>`).join('')}`,btn('保存关联','save-links',`data-id="${p.id}"`,true));return;}
    if(action==='save-links'){const ids=[...document.querySelectorAll('[name=topic-link]:checked')].map(n=>n.value);if(ids.length>6)throw Error('每个专场最多6条脚本');db.topics.filter(t=>t.projectId===p.id).forEach(t=>t.projectId=null);ids.forEach(id=>db.topics.find(t=>t.id===id).projectId=p.id);p.topicIds=ids;save();close();render();return;}
    if(action==='new-asset'){dialog('建立参考专题',`<div class="formgrid"><label>专题名称<input id="asset-name"></label><label>分类／标签<input id="asset-category" placeholder="例如：黑色造型／主舞台"></label><label>类型<select id="asset-kind">${[['scene','场景'],['wardrobe','服装'],['aesthetic','共享审美']].map(([k,l])=>`<option value="${k}" ${e.dataset.kind===k?'selected':''}>${l}</option>`).join('')}</select></label><label>所属专场<select id="asset-project"><option value="">不关联</option>${db.projects.map(p=>`<option value="${p.id}" ${p.id===e.dataset.project?'selected':''}>${esc(p.title)}</option>`).join('')}</select></label></div>`,btn('建立专题','create-asset','',true));return;}
    if(action==='create-asset'){const name=$('#asset-name').value.trim();if(!name)throw Error('请填写专题名称');const asset={id:C.uid(),name,category:$('#asset-category').value,kind:$('#asset-kind').value,projectId:$('#asset-project').value||null,requirements:'',dimensions:'',dimensionsConfirmed:false,inventory:'',analysis:'',files:[],frames:[],outfits:[],proposal:C.slot('AI效果参考')};if(asset.kind==='aesthetic'){const all=globalAssets();all.push(asset);localStorage.setItem('lance_studio_aesthetic',JSON.stringify(all));route={view:'aesthetic'};}else{db.assets.push(asset);route={view:'asset',id:asset.id};save();}close();render();return;}
    if(action==='global-asset'){const a=globalAssets().find(a=>a.id===e.dataset.id);dialog(a.name,`<div class="grid">${a.files.map(f=>mediaMarkup(f)).join('')}</div>`,upload('上传审美参考','global',`data-id="${a.id}"`,'image/*,video/*'));return;}
    if(action==='frames'){await withJob('提取候选关键帧',1,async()=>{await extractAssetFrames(a,Number(e.dataset.file));progress('关键帧已保存');});return;}
    if(action==='analyze-asset'){await withJob('分析项目资料',1,async()=>{await analyzeAsset(a);progress('分析已保存，等待你核对');});return;}
    if(action==='backup'){await withJob('完整备份',1,backup);return;}
  }catch(error){notify(error.message);}
});
window.addEventListener('beforeunload',event=>{if(job){event.preventDefault();event.returnValue='';}});
try{db=read(scope);save();render();api('health',undefined,{timeout:5000}).then(h=>{health=h;for(const k of ['text','image','video'])if(!settings[k+'Model'])settings[k+'Model']=h.models[k]||'';render();}).catch(()=>{});}catch(error){$('#app').textContent=error.message;}
