const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../studio-core');const A=require('../studio-aesthetic');
test('新参考默认不冒充已确认授权并保留来源字段',()=>{const a=A.entry('网页参考');assert.equal(a.sourceUsage,'unconfirmed');assert.equal(a.sourceSite,'');});
test('分类与标签支持用户自定义，并按搜索、收藏筛选',()=>{const a=A.entry('长镜头');a.category='现场机械装置';a.tags=A.tags('运镜，暖光,运镜');a.notes='环绕运动';a.favorite=true;assert.deepEqual(a.tags,['运镜','暖光']);assert.equal(A.filter([a],{category:'现场机械装置',tag:'运镜',search:'环绕',favorite:true}).length,1);assert.equal(A.filter([a],{category:'摄影参考'}).length,0);});
test('历史封面统一归入封面参考，并可在子级交叉筛选',()=>{const folders=[{id:'history',name:'初瑞雪过往封面全集'},{id:'upgrade',name:'增量优化｜封面建议'}],photo={...A.entry('人物封面'),category:'历史参考｜人物照片封面',tags:['历史封面','人物照片'],folderIds:['history']},text={...A.entry('字体封面'),category:'历史参考｜纯字体模板',tags:['历史封面','纯字体'],folderIds:['history']},upgrade={...A.entry('新建议'),category:'摄影参考',tags:[],folderIds:['upgrade']};assert.equal(A.categoryOf(photo,folders),'封面参考');assert.equal(A.categoryOf(upgrade,folders),'封面参考');assert.deepEqual(A.viewFilter([photo,text,upgrade],{category:'封面参考',coverType:'过往封面',coverFolders:folders}).map(x=>x.name).sort(),['人物封面','字体封面']);assert.equal(A.viewFilter([photo,text,upgrade],{category:'封面参考',coverType:'人物照片',coverFolders:folders})[0].name,'人物封面');assert.equal(A.viewFilter([photo,text,upgrade],{category:'封面参考',coverType:'纯字体',coverFolders:folders})[0].name,'字体封面');assert.equal(A.viewFilter([photo,text,upgrade],{category:'封面参考',coverType:'增量优化',coverFolders:folders})[0].name,'新建议');});
test('链接允许分享文字，不允许脚本协议和内嵌凭据',()=>{assert.equal(A.link('作品 https://example.com/watch?v=1，复制打开'),'https://example.com/watch?v=1');for(const url of ['javascript:alert(1)','data:text/html,test','file:///private/file','https://user:pass@example.com'])assert.throws(()=>A.link(url));});
test('旧版审美记录迁移保留分类、标签、笔记、图与来源，重复迁移不重复',()=>{const old=[{id:'old',title:'原参考',type:'声光电',tags:['舞台'],note:'追光',url:'https://example.com/work',image:'data:image/png;base64,aGVsbG8='}];const first=A.migrate([],old);assert.equal(first[0].category,'声光电');assert.equal(first[0].legacyImage,old[0].image);assert.equal(A.migrate(first,old).length,1);assert.equal(old[0].note,'追光');});
test('共享素材只有明确选用的项目可进入AI上下文，身份不混用',()=>{const a=A.entry('参考');a.usedIn=[{scope:'personal',id:'p'}];assert.equal(A.forProject([a],'personal','p').length,1);assert.equal(A.forProject([a],'xinxuan','p').length,0);assert.equal(A.forProject([a],'personal',null).length,0);});
test('旧共享库按历史归属拆成两个空间，未归属审美默认保留在个人',()=>{const work=A.entry('工作参考'),personal=A.entry('个人参考'),direct=A.entry('旧直连工作参考'),loose=A.entry('长期收藏');work.folderIds=['wf'];personal.usedIn=[{scope:'personal',id:'pp'}];direct.folderIds=['direct'];direct.usedIn=[{scope:'xinxuan',id:'wp'}];const folders=[{id:'wf',name:'工作项目参考'},{id:'direct',name:'旧直连文件夹'},{id:'loose',name:'未归属'}],data={xinxuan:{projects:[{folderIds:['wf']}]},personal:{projects:[{id:'pp'}]}};const split=A.splitLegacy([work,personal,direct,loose],folders,data);assert.deepEqual(split.xinxuan.items.map(x=>x.name),['工作参考','旧直连工作参考']);assert.deepEqual(split.personal.items.map(x=>x.name),['个人参考','长期收藏']);assert.deepEqual(split.xinxuan.folders.map(x=>x.id),['wf','direct']);assert.deepEqual(split.personal.folders.map(x=>x.id),['loose']);assert.equal(work.folderIds[0],'wf');});
test('同一旧文件夹若历史上确实被两空间使用，拆分后成为互不影响的副本',()=>{const a=A.entry('共同旧参考');a.folderIds=['both'];const folder={id:'both',name:'旧共享文件夹'},split=A.splitLegacy([a],[folder],{xinxuan:{topics:[{folderIds:['both']}]},personal:{topics:[{folderIds:['both']}]}});split.xinxuan.items[0].name='只改工作';assert.equal(split.personal.items[0].name,'共同旧参考');assert.notEqual(split.xinxuan.items[0],split.personal.items[0]);assert.equal(folder.name,'旧共享文件夹');});
test('删除先移入可恢复的回收站，不会改写原数据',()=>{const original=A.entry('不能误删的参考');original.folderIds=['project'];const items=[original],moved=A.trashItem(items,original.id,'2026-09-20T00:00:00.000Z');assert.equal(items.length,1);assert.equal(moved.items.length,0);assert.equal(moved.deleted.name,original.name);assert.equal(moved.deleted.deletedAt,'2026-09-20T00:00:00.000Z');assert.deepEqual(moved.deleted.folderIds,['project']);const restored=A.restoreItem(moved.items,[moved.deleted],original.id,()=>'new-id');assert.equal(restored.items.length,1);assert.equal(restored.trash.length,0);assert.equal(restored.restored.id,original.id);assert.equal('deletedAt' in restored.restored,false);});
test('恢复时若ID已被备份恢复占用，会换新ID不覆盖',()=>{const a=A.entry('参考'),deleted={...a,deletedAt:'2026'};const result=A.restoreItem([a],[deleted],a.id,()=>'safe-copy');assert.equal(result.items.length,2);assert.equal(result.restored.id,'safe-copy');});
test('项目文字、封面样式和图片可提取为不关联项目的独立参考',()=>{
  const project=C.project('秋冬服装大秀专场');project.idea='秋冬大秀';project.fields.outline='以四季为结构';
  const topic=C.topic('落叶步道',project.id);topic.quick.fields.description='人物走过落叶步道';const cover=C.ensureCover(topic);cover.recommendation='首选近景';cover.options[0].headline='入冬';
  C.putVersion(cover.options[0].image,{id:'c',kind:'image',localId:'cover.jpg',verified:true});C.putVersion(topic.quick.images[0],{id:'v',kind:'image',localId:'visual.jpg',verified:true});
  const result=A.projectReferences(project,[topic]);assert.ok(result.some(item=>item.category==='创意文字'));assert.ok(result.some(item=>item.category==='封面参考'&&item.files[0].localId==='cover.jpg'));assert.ok(result.some(item=>item.name==='落叶步道 · 视觉图片'&&item.files[0].localId==='visual.jpg'));
  for(const item of result){assert.deepEqual(item.usedIn,[]);assert.deepEqual(item.folderIds,[]);assert.equal('projectId' in item,false);}
});
test('相同内容重复提取不会形成重复参考卡',()=>{const project=C.project('参考源');project.fields.outline='一段内容';const extracted=A.projectReferences(project,[]),first=A.mergeExtracted([],extracted),second=A.mergeExtracted(first.items,extracted);assert.equal(first.added.length,1);assert.equal(second.added.length,0);assert.equal(second.items.length,1);});
