// Isolated browser profile, synthetic fixtures only, no paid AI calls or user's data.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const url='http://127.0.0.1:8000';await page.goto(url);await page.getByRole('button',{name:'新建单条脚本',exact:true}).click();await page.locator('#new-title').fill('【自动化验收】下播后的最后一束光');await page.locator('#new-idea').fill('软件测试用稿，非正式创意：从主播下班时的疲惫切入，不虚构产品功能。');await page.getByRole('button',{name:'创建并开始',exact:true}).click();
 await page.getByRole('button',{name:'下载PPT',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notification').textContent.includes('仍缺少'));assert.equal(await page.getByRole('button',{name:'确认汇报方向，进入深化'}).isDisabled(),true);
 for(const k of ['outline','meaning','description','dialogue','atmosphere','camera','script']){const f=page.locator(`[data-field="topics.0.quick.fields.${k}"]`);await f.fill('测试内容：凌晨下播，人物收起话筒，留下一束工作灯。产品性能须实测确认。');await f.blur();}
 await page.getByRole('button',{name:'AI补全缺项',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#notification').textContent.includes('模型ID'));assert.equal(await page.locator('[data-field="topics.0.quick.fields.outline"]').inputValue(),'测试内容：凌晨下播，人物收起话筒，留下一束工作灯。产品性能须实测确认。');
 // Synthetically simulate provider outputs via ordinary verified upload UI in this isolated profile.
 const fixtures=path.resolve(__dirname,'../test-output');
 for(let i=0;i<3;i++){await page.locator(`input[data-upload="slot"][data-path="topics.0.quick.images.${i}"]`).setInputFiles(path.join(fixtures,'fixture.png'));await page.waitForFunction(()=>!document.querySelector('.job'));}
 for(const k of ['opening','middle','ending']){await page.locator(`input[data-upload="slot"][data-path="topics.0.quick.videos.${k}"]`).setInputFiles(path.join(fixtures,'fixture.mp4'));await page.waitForFunction(()=>!document.querySelector('.job'));}
 assert.equal(await page.getByRole('button',{name:'确认汇报方向，进入深化'}).isEnabled(),true);await page.screenshot({path:path.join(fixtures,'工作台_验收截图.png'),fullPage:true});
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'下载PPT',exact:true}).click();const download=await downloadPromise;await download.saveAs(path.join(fixtures,'浏览器导出_测试素材.pptx'));await page.waitForFunction(()=>!document.querySelector('.job'));
 await page.reload();await page.getByRole('button',{name:'成果与备份',exact:true}).click();assert.equal(await page.getByRole('button',{name:'重新下载',exact:true}).count(),1);const again=page.waitForEvent('download');await page.getByRole('button',{name:'重新下载',exact:true}).click();assert.ok((await again).suggestedFilename().endsWith('.pptx'));
 await page.getByRole('button',{name:'脚本与汇报',exact:true}).click();await page.getByRole('button',{name:'快速汇报',exact:true}).click();await page.getByRole('button',{name:'确认汇报方向，进入深化'}).click();assert.equal(await page.getByRole('heading',{name:'25镜工程',exact:true}).count(),1);await page.getByRole('button',{name:'预览汇报',exact:true}).click();assert.ok(await page.getByRole('dialog').getByText('完整AI成片参考',{exact:true}).count());await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.locator('#scope').selectOption('personal');assert.equal(await page.getByRole('heading',{name:'【自动化验收】下播后的最后一束光',exact:true}).count(),0);await page.locator('#scope').selectOption('xinxuan');assert.equal(await page.getByRole('heading',{name:'【自动化验收】下播后的最后一束光',exact:true}).count(),1);
 await page.getByRole('button',{name:'新建专场',exact:true}).click();await page.locator('#new-title').fill('【自动化验收】专场');await page.getByRole('button',{name:'创建并开始',exact:true}).click();assert.ok(await page.getByText('6条故事脚本',{exact:true}).count());
 await page.getByRole('button',{name:'场景库',exact:true}).click();await page.getByRole('button',{name:'建立资料专题',exact:true}).click();await page.locator('#asset-name').fill('【自动化验收】6米场地');await page.getByRole('button',{name:'建立专题',exact:true}).click();await page.locator('[data-field="assets.0.dimensions"]').fill('长6米宽4米，层高待核实');await page.locator('[data-field="assets.0.dimensions"]').blur();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(fixtures,'场景库_移动端.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: browser create/save/reload, missing-field gate, provider error preservation, 3 images + 3 video upload, PPT download & redownload, deep preview, scope isolation, project and scene forms, mobile layout; no live AI calls.');
})().catch(e=>{console.error(e);process.exit(1);});
