const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../studio-core.js');
function readyTopic(){const t=C.topic('测试脚本');for(const[k]of C.QUICK)t.quick.fields[k]='完整测试内容';for(const s of t.quick.images)C.putVersion(s,{kind:'image',verified:true,localId:C.uid()+'.png',source:'upload'});for(const[k]of C.PHASES)C.putVersion(t.quick.videos[k],{kind:'video',verified:true,localId:C.uid()+'.mp4',duration:8,source:'ai'});return t;}
test('快速汇报：文字或提示词不能替代实际媒体',()=>{const t=C.topic();t.quick.images.forEach(s=>s.prompt='图片描述');assert.equal(C.quickStatus(t).ready,false);assert.equal(C.quickStatus(t).images,0);assert.equal(C.quickStatus(readyTopic()).ready,true);});
test('快速汇报拒绝5秒、缺时长、非AI视频和超过5张图',()=>{for(const duration of[5,10,undefined,NaN]){const t=readyTopic();C.selected(t.quick.videos.opening).duration=duration;assert.equal(C.quickStatus(t).ready,false);}const t=readyTopic();C.selected(t.quick.videos.middle).source='upload';assert.equal(C.quickStatus(t).ready,false);t.quick.images.push(C.slot('4'),C.slot('5'),C.slot('6'));assert.equal(C.quickStatus(t).ready,false);});
test('专场必须是6个不同脚本，且每条全部齐备',()=>{const p=C.project('测试专场'),items=Array.from({length:6},readyTopic);for(const[k]of C.SESSION)p.fields[k]='专场内容';p.topicIds=items.map(t=>t.id);assert.equal(C.sessionStatus(p,items).ready,true);assert.equal(C.sessionStatus(p,items).videos,18);p.topicIds[5]=p.topicIds[0];assert.equal(C.sessionStatus(p,items).ready,false);});
test('锁定保护、单图历史和旧数据导入不覆盖原始资料',()=>{const s=C.slot('图');C.putVersion(s,{localId:'a'});const old=s.selectedId;C.putVersion(s,{localId:'b'});assert.equal(s.versions.length,2);assert.notEqual(s.selectedId,old);s.locked=true;assert.throws(()=>C.putVersion(s,{}),/锁定/);const original={id:1,title:'旧稿',script:'脚本',referenceImages:['external']};assert.deepEqual(C.importLegacy(original).legacy,original);assert.equal(C.quickStatus(C.importLegacy(original)).images,0);});
test('严格AI结构：损坏JSON、24镜、无摄影不得覆盖',()=>{assert.throws(()=>C.parseJSON('{'),/JSON/);assert.deepEqual(C.parseJSON('```json\n{"a":1}\n```'),{a:1});assert.throws(()=>C.validateShots({shots:[]}),/25/);assert.throws(()=>C.validateQuick({fields:{}},3),/创意大纲/);});
test('25镜深化需要AI图、完整成片且与当前镜头和配乐一致',()=>{const t=readyTopic();t.quick.approved={fields:{script:'确认的脚本'}};for(const[k]of C.DEEP)t.deep.fields[k]='执行方案';t.deep.shots=C.validateShots({shots:Array.from({length:25},()=>({visual:'人物走进场景',camera:'中景推镜',duration:2}))});for(const s of t.deep.shots){C.putVersion(s.image,{kind:'image',verified:true,source:'ai',localId:'image'});C.putVersion(s.video,{kind:'video',verified:true,source:'ai',duration:2,localId:'video'});}assert.equal(C.deepStatus(t).ready,false);t.deep.film={kind:'video',source:'ai-assembly',verified:true,localId:'film',duration:50,fingerprint:C.shotFingerprint(t.deep.shots),bgmId:null};assert.equal(C.deepStatus(t).ready,true);t.deep.shots[0].visual='修改后';assert.equal(C.deepStatus(t).ready,false);t.deep.film.fingerprint=C.shotFingerprint(t.deep.shots);t.deep.bgm={localId:'new-audio'};assert.equal(C.deepStatus(t).ready,false);});
module.exports={readyTopic};
