const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../studio-core.js');
function readyTopic(){const t=C.topic('测试脚本');for(const[k]of C.QUICK)t.quick.fields[k]='完整测试内容';const cover=C.ensureCover(t);cover.recommendation='A最符合本条视频的情绪钩子';cover.options.forEach((o,i)=>{o.headline='封面标题'+(i+1);o.subheadline='辅助文案'+(i+1);o.description='构图与点击逻辑'+(i+1);o.image.prompt='无字竖版封面底图'+(i+1);C.putVersion(o.image,{kind:'image',verified:true,localId:C.uid()+'.png',source:'ai'});});for(const s of t.quick.images)C.putVersion(s,{kind:'image',verified:true,localId:C.uid()+'.png',source:'upload'});for(const[k]of C.PHASES)C.putVersion(t.quick.videos[k],{kind:'video',verified:true,localId:C.uid()+'.mp4',duration:8,source:'ai'});return t;}
test('快速汇报：文字或提示词不能替代实际媒体',()=>{const t=C.topic();t.quick.images.forEach(s=>s.prompt='图片描述');assert.equal(C.quickStatus(t).ready,false);assert.equal(C.quickStatus(t).images,0);assert.equal(C.quickStatus(readyTopic()).ready,true);});
test('快速汇报强制要求三套完成的视频封面推荐',()=>{const t=readyTopic();assert.equal(C.quickStatus(t).covers,3);C.selected(t.quick.cover.options[1].image).verified=false;assert.equal(C.quickStatus(t).ready,false);assert.match(C.quickStatus(t).missing.join('、'),/封面B实际图片/);});
test('快速汇报拒绝5秒、缺时长、非AI视频和超过5张图',()=>{for(const duration of[5,10,undefined,NaN]){const t=readyTopic();C.selected(t.quick.videos.opening).duration=duration;assert.equal(C.quickStatus(t).ready,false);}const t=readyTopic();C.selected(t.quick.videos.middle).source='upload';assert.equal(C.quickStatus(t).ready,false);t.quick.images.push(C.slot('4'),C.slot('5'),C.slot('6'));assert.equal(C.quickStatus(t).ready,false);});
test('兼容默认6条的旧专场，每条必须齐备且不重复',()=>{const p=C.project('测试专场'),items=Array.from({length:6},readyTopic);for(const[k]of C.SESSION)p.fields[k]='专场内容';p.topicIds=items.map(t=>t.id);assert.equal(C.sessionStatus(p,items).ready,true);assert.equal(C.sessionStatus(p,items).videos,18);p.topicIds[5]=p.topicIds[0];assert.equal(C.sessionStatus(p,items).ready,false);});
test('锁定保护、单图历史和旧数据导入不覆盖原始资料',()=>{const s=C.slot('图');C.putVersion(s,{localId:'a'});const old=s.selectedId;C.putVersion(s,{localId:'b'});assert.equal(s.versions.length,2);assert.notEqual(s.selectedId,old);assert.equal(C.selected(s).localId,'b');s.selectedId=old;assert.equal(C.selected(s).localId,'a');s.locked=true;assert.throws(()=>C.putVersion(s,{}),/锁定/);const original={id:1,title:'旧稿',script:'脚本',referenceImages:['external']};assert.deepEqual(C.importLegacy(original).legacy,original);assert.equal(C.quickStatus(C.importLegacy(original)).images,0);});
test('严格AI结构：损坏JSON、24镜、无摄影不得覆盖',()=>{assert.throws(()=>C.parseJSON('{'),/JSON/);assert.deepEqual(C.parseJSON('```json\n{"a":1}\n```'),{a:1});assert.throws(()=>C.validateShots({shots:[]}),/25/);assert.throws(()=>C.validateQuick({fields:{}},3),/创意大纲/);});
test('25镜深化需要AI图、完整成片且与当前镜头和配乐一致',()=>{const t=readyTopic();t.quick.approved={fields:{script:'确认的脚本'}};for(const[k]of C.DEEP)t.deep.fields[k]='执行方案';t.deep.shots=C.validateShots({shots:Array.from({length:25},()=>({visual:'人物走进场景',camera:'中景推镜',duration:2}))});for(const s of t.deep.shots){C.putVersion(s.image,{kind:'image',verified:true,source:'ai',localId:'image'});C.putVersion(s.video,{kind:'video',verified:true,source:'ai',duration:2,localId:'video'});}assert.equal(C.deepStatus(t).ready,false);t.deep.film={kind:'video',source:'ai-assembly',verified:true,localId:'film',duration:50,fingerprint:C.shotFingerprint(t.deep.shots),bgmId:null};assert.equal(C.deepStatus(t).ready,true);t.deep.shots[0].visual='修改后';assert.equal(C.deepStatus(t).ready,false);t.deep.film.fingerprint=C.shotFingerprint(t.deep.shots);t.deep.bgm={localId:'new-audio'};assert.equal(C.deepStatus(t).ready,false);});
test('月度预算只做参考估算，默认10条脚本和6条深化不变成限额',()=>{const plan=C.budgetPlan({monthlyCny:800,projects:3,scripts:10,deepScripts:6}),estimate=C.monthlyCostRange(plan);assert.deepEqual(plan,{monthlyCny:800,projects:3,scripts:10,deepScripts:6});assert.deepEqual(estimate.videoSeconds,[690,840]);assert.equal(estimate.images,220);assert.ok(estimate.cost[0]>=599&&estimate.cost[1]<=710);assert.equal(C.budgetPlan({scripts:0}).scripts,10);});
test('批量生成费用只统计缺失素材',()=>{const t=C.topic('预算测试'),quick=C.quickGenerationCost(t);assert.deepEqual({images:quick.images,videoSeconds:quick.videoSeconds},{images:6,videoSeconds:24});for(const s of t.quick.images)C.putVersion(s,{kind:'image',verified:true,source:'ai',localId:'image'});assert.equal(C.quickGenerationCost(t).images,3);t.deep.shots=C.validateShots({shots:Array.from({length:25},()=>({visual:'画面',camera:'中景',duration:3}))});assert.deepEqual(C.deepGenerationCost(t,'image'),{images:25,videoSeconds:0,cost:6.6});assert.deepEqual(C.deepGenerationCost(t,'video'),{images:0,videoSeconds:75,cost:54});});
module.exports={readyTopic};
