const {test}=require('node:test'),assert=require('node:assert/strict');
const D=require('../studio-director'),R=require('../studio-reverse'),P=require('../studio-ppt'),fs=require('node:fs'),vm=require('node:vm');
function fixture(style='narrative'){
 const r=R.create('参考作品');r.frames=[{localId:'test.png',timestamp:3,kind:'image',verified:true,source:'video-frame'}];
 D.acceptOverview(r,{summary:'原片故事',relationships:'关系待核对',concept:'延迟揭示信息',questions:'未知音轨',beats:[{title:'开场',claim:'人物进入',basis:'inferred',frameIndices:[0]}]},D.fingerprint(r));D.confirm(r);D.startPlan(r,style);return r;
}
function report(r){return {review:'资源及原片关系待核对',pages:r.directorPlan.chapters.filter(c=>c.enabled).map(c=>({slotId:c.id,title:c.title,section:c.section,basis:'proposal',points:['具体处理与本段情绪相连'],notes:'讲清本片选择与取舍，未知资源需进一步确认',frameIndices:[0]}))};}
function script(){return {title:'新故事',logline:'新人物的目标',synopsis:'新人物面对阻碍，选择行动并产生改变',mechanism:'借鉴延迟揭示机制，但改为新的事件',differences:'不同人物、场景、行动与结局',feasibility:'两演员一个场景，场地尚未确认',scenes:Array.from({length:3},(_,i)=>({title:'场次'+i,action:'人物采取具体行动',purpose:'改变人物对局面的认识',camera:'先看反应，再揭示事件',sound:'拟定环境声与停顿',production:'单场景可实现，需核对空间'}))};}
function readyScript(r){Object.assign(r.directorPlan.transfer,{avoid:'不搬原片角色和标志道具',target:'新的主题和人物需求',conditions:'2人1场景'});D.acceptScript(r,script(),D.scriptRequestKey(r));D.confirmScript(r);}
test('两案例生成不同的24页可编辑结构，主讲20页＋附录4页',()=>{for(const style of ['narrative','visual']){const r=fixture(style),p=r.directorPlan;assert.equal(p.chapters.length,24);assert.equal(p.chapters.filter(c=>c.group==='main').length,20);assert.equal(p.chapters.filter(c=>c.group==='appendix').length,4);assert.equal(D.planReady(r),false);assert.throws(()=>D.startPlan(r,style),/避免覆盖/);}assert.notDeepEqual(fixture().directorPlan.chapters,fixture('visual').directorPlan.chapters);});
test('修改提纲只使汇报确认过期，不使原片证据或故事确认失效',()=>{const r=fixture();D.confirmPlan(r);const source=D.fingerprint(r);assert.ok(D.planReady(r));r.directorPlan.goal='新汇报目标';assert.ok(D.confirmed(r));assert.equal(D.fingerprint(r),source);assert.equal(D.planReady(r),false);assert.throws(()=>D.reportPrompt(r,{shots:[]}),/提纲/);D.confirmPlan(r);assert.ok(D.planReady(r));});
test('删减可选章节不强迫凑五类，但必须保留边界，重复编号不可确认',()=>{const r=fixture();r.directorPlan.chapters.filter(c=>c.section==='decisions').forEach(c=>c.enabled=false);D.confirmPlan(r);D.acceptReport(r,report(r),D.reportKey(r));assert.deepEqual(D.reportIssues(r),[]);r.directorPlan.chapters.find(c=>c.section==='limits').enabled=false;assert.throws(()=>D.confirmPlan(r),/附录/);});
test('生成是草稿，确认后才能导出主讲版，编辑讲稿会撤销就绪状态',()=>{const r=fixture();D.confirmPlan(r);D.acceptReport(r,report(r),D.reportKey(r));assert.ok(D.reportGenerated(r));assert.equal(D.reportReady(r),false);assert.throws(()=>D.deck(r),/核对/);assert.equal(D.deck({...r,directorExportVariant:'draft'}).draft,true);D.approveReport(r);assert.ok(D.reportReady(r));const main=D.deck({...r,directorExportVariant:'main'}),full=D.deck({...r,directorExportVariant:'full'});assert.equal(main.slides.length,21);assert.equal(full.slides.length,27);assert.ok(!main.slides.some(p=>p.title==='原片依据索引'));assert.ok(full.slides.some(p=>p.title==='原片依据索引'));assert.equal(main.slides[1].evidence,'画面参考：原片截帧');assert.match(main.slides[1].notes,/3.00秒/);r.director.report.pages[0].notes='我改过的讲稿';assert.equal(D.reportReady(r),false);});
test('缺页保留付费正文、补页保持用户修改、不循环收费',()=>{const r=fixture();D.confirmPlan(r);const raw=report(r),last=raw.pages.pop();D.acceptReport(r,raw,D.reportKey(r));assert.ok(D.reportGenerated(r));assert.match(D.reportIssues(r).join(''),/缺少/);r.director.report.pages[0].notes='手动修改';const base=D.reportRecovery(r);assert.equal(base.missingSlots[0].id,last.slotId);D.acceptSupplement(r,{pages:[last],review:'补齐'},base.key,base.baseRaw);assert.equal(r.director.report.pages[0].notes,'手动修改');assert.deepEqual(D.reportIssues(r),[]);assert.equal(D.reportReady(r),false);});
test('空手动补页不能崩溃渲染，无法确认导出',()=>{const r=fixture();D.confirmPlan(r);const raw=report(r);raw.pages.pop();D.acceptReport(r,raw,D.reportKey(r));r.director.report.pages.push({slotId:'evidence',title:'待写',section:'limits',basis:'proposal',points:[''],notes:'',frameIndices:[]});assert.equal(D.reportRecovery(r),null);assert.ok(D.reportIssues(r).length);assert.throws(()=>D.approveReport(r));});
test('新故事需求必填，不会把原片主线自动当作新剧本',()=>{const r=fixture();r.directorPlan.mode='adapt';assert.throws(()=>D.scriptPrompt(r),/不能照搬/);assert.throws(()=>D.confirmPlan(r),/新故事/);Object.assign(r.directorPlan.transfer,{avoid:'禁搬情节',target:'原创要求',conditions:'条件待定'});const prompt=D.scriptPrompt(r);assert.match(prompt,/不是替原片换人名/);assert.match(prompt,/可拍场次/);assert.match(prompt,/原创要求/);});
test('新剧本可编辑、确认后带入提纲和独立脚本，不拷贝原片媒体',()=>{const r=fixture();const original=JSON.stringify(r.director.overview);readyScript(r);assert.ok(D.scriptConfirmed(r));assert.equal(r.directorPlan.mode,'adapt');assert.equal(r.directorPlan.story,script().synopsis);D.confirmPlan(r);const t=D.toTopic(r);assert.equal(t.title,'新故事');assert.match(t.quick.fields.script,/场次2/);assert.equal(t.projectId,null);assert.equal(t.quick.images[0].versions.length,0);assert.equal(t.sourceReverse.id,r.id);assert.equal(JSON.stringify(r.director.overview),original);D.acceptReport(r,report(r),D.reportKey(r));D.approveReport(r);assert.equal(D.deck(r).slides[0].title,'新故事');r.directorPlan.script.scenes[0].action='用户的新修改';assert.equal(D.scriptConfirmed(r),false);assert.equal(D.planReady(r),false);assert.equal(D.reportReady(r),false);});
test('需求或手动剧本在请求期间变化时不覆盖，旧版本保留',()=>{const r=fixture();readyScript(r);const old=JSON.stringify(r.directorPlan.script),key=D.scriptRequestKey(r);r.directorPlan.script.synopsis='手动改稿';assert.throws(()=>D.acceptScript(r,script(),key),/未覆盖/);D.acceptScript(r,script(),D.scriptRequestKey(r));assert.equal(r.directorPlan.scriptVersions.length,1);assert.equal(r.directorPlan.scriptVersions[0].script.synopsis,'手动改稿');assert.notEqual(JSON.stringify(r.directorPlan.scriptVersions[0].script),old);r.directorPlan.transfer.target='新需求';assert.equal(D.scriptCurrent(r),false);assert.throws(()=>D.toTopic(r));});
test('案例提示包含已确认新剧本，强调机制迁移且不机械三格',()=>{const r=fixture('visual');readyScript(r);D.confirmPlan(r);const prompt=D.reportPrompt(r,{shots:[]});assert.match(prompt,/概念视觉型/);assert.match(prompt,/新故事/);assert.match(prompt,/不要每页机械套/);assert.match(prompt,/slotId/);assert.match(prompt,/两演员一个场景/);});
function adapter(r,reply){let calls=0;const context=vm.createContext({StudioDirector:D,document:{addEventListener(){}},stop:false,job:null,ensureService:async()=>{},withJob:async(t,n,fn)=>fn(),api:async()=>{calls++;return {text:JSON.stringify(reply)};},save(){},render(){},notify(){},recordTextUsage(){},progress(){},db:{reverse:[r],topics:[]},route:{view:'reverse-detail',id:r.id}});vm.runInContext(fs.readFileSync(require.resolve('../studio-director-ui'),'utf8'),context);return {context,calls:()=>calls};}
test('创意转化只一次文字调用，确认和建立脚本免费且重复点击不重复建',async()=>{const r=fixture();Object.assign(r.directorPlan.transfer,{avoid:'不搬角色',target:'原创故事',conditions:'小型剧组'});const x=adapter(r,script());await x.context.directorAction('reverse-director-script',{},r);assert.equal(x.calls(),1);await x.context.directorAction('reverse-director-script-confirm',{},r);await x.context.directorAction('reverse-director-topic',{},r);await x.context.directorAction('reverse-director-topic',{},r);assert.equal(x.calls(),1);assert.equal(x.context.db.topics.length,1);});
test('等待正文时用户编辑不会被API结果覆盖，原始回答仍保存',async()=>{const r=fixture();D.confirmPlan(r);D.acceptReport(r,report(r),D.reportKey(r));const x=adapter(r,report(r));x.context.api=async()=>{r.director.report.pages[0].notes='等待时编辑';return {text:JSON.stringify(report(r))};};await assert.rejects(x.context.directorResponse(r,'report','prompt',D.reportKey(r)),/未覆盖/);assert.equal(r.director.report.pages[0].notes,'等待时编辑');assert.ok(r.directorResponses.report.raw);});
