// Synthetic microphone in isolated Chrome; speech + paid model responses mocked.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome',args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/profile-seed?*',r=>r.fulfill({json:{fields:{}}}));
 await page.addInitScript(()=>{if(!localStorage.getItem('fragment-test')){localStorage.setItem('fragment-test','1');localStorage.setItem('xuan_ti_ku_inspirations_xinxuan',JSON.stringify([{id:5,title:'历史碎片',rawText:'旧版的一束灯光',organizedText:'旧整理保留',type:'text'}]));}class FakeSpeech{start(){setTimeout(()=>this.onresult?.({resultIndex:0,results:[Object.assign([{transcript:'【模拟语音识别】人物在走廊想起一件小事。'}],{isFinal:true})]}),200);}stop(){this.onend?.();}abort(){}}window.SpeechRecognition=FakeSpeech;});
 const nav=()=>page.locator('nav [data-view="fragments"]').click(),click=t=>page.getByRole('button',{name:t,exact:true}).click(),read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('lance_studio_v2_xinxuan'))),idle=()=>page.waitForFunction(()=>!document.querySelector('.job'));
 await page.goto('http://127.0.0.1:8000/');await nav();assert.equal((await read()).fragments.length,1);await page.locator('#fragment-draft').fill('没想完整也要存下的草稿');await page.reload();await nav();assert.equal(await page.locator('#fragment-draft').inputValue(),'没想完整也要存下的草稿');assert.equal((await read()).fragments.length,1);await click('存下这条想法');assert.equal((await read()).fragments.length,2);
 await page.locator('#fragment-speech-consent').check();await click('开始语音记录');await page.waitForFunction(()=>document.querySelector('#fragment-record-state').textContent.includes('正在录音 2秒'));await click('停止并保存录音');await page.waitForFunction(()=>document.querySelector('[data-action="fragment-record"]'));let data=await read();assert.equal(data.fragments.length,3);const voice=data.fragments.find(n=>n.type==='audio');assert.match(voice.rawText,/模拟语音识别/);assert.ok(voice.audioKey);
 await page.reload();await nav();await page.locator(`[data-action="fragment-open"][data-id="${voice.id}"]`).click();await page.locator('audio').evaluate(a=>new Promise((resolve,reject)=>{if(a.readyState>=1)return resolve();a.onloadedmetadata=resolve;a.onerror=()=>reject(Error('Audio cannot be decoded'));}));const download=page.waitForEvent('download');await click('下载原录音');await (await download).saveAs(path.resolve(__dirname,'../test-output/模拟麦克风录音.webm'));await click('关闭');
 await page.evaluate(()=>navigator.mediaDevices.getUserMedia=()=>Promise.reject(new DOMException('Synthetic denial','NotAllowedError')));await click('开始语音记录');await page.waitForFunction(()=>document.querySelector('#notification').textContent.includes('未开始录音'));assert.equal((await read()).fragments.length,3);
 await page.route('**/api/chat',async r=>{assert.ok(r.request().postDataJSON().prompt.includes('原始记录'));await r.fulfill({json:{text:JSON.stringify({title:'【模拟】灯光与人物',essence:'模拟核心',hook:'模拟切入',usable:'短片，先采访',connections:'结合历史碎片与语音',questions:'人物经历待核实',tags:['光']})}});});await page.locator(`[data-action="fragment-refine"][data-id="${voice.id}"]`).click();await idle();data=await read();assert.equal(data.fragments.find(n=>n.id===voice.id).analyses.length,1);assert.equal(data.fragments.find(n=>n.id===voice.id).rawText,voice.rawText);
 await page.locator('[data-fragment-select]').nth(0).check();await page.locator('[data-fragment-select]').nth(1).check();await click('组合选中的灵感');await idle();assert.equal((await read()).fragmentPlans.length,1);await click('转为新选题');assert.equal((await read()).topics[0].sourceFragments.length,2);assert.equal((await read()).topics[0].quick.fields.outline,'');
 await page.locator('#scope').selectOption('personal');await nav();assert.equal(await page.locator('.grid .card').count(),0);await page.locator('#scope').selectOption('xinxuan');await nav();assert.equal((await read()).fragments.length,3);
 await page.locator('nav [data-view="archive"]').click();const backup=page.waitForEvent('download');await page.locator('[data-action="backup"]').click();const file=path.resolve(__dirname,'../test-output/语音灵感备份.zip');await (await backup).saveAs(file);await idle();const zip=await require('jszip').loadAsync(fs.readFileSync(file));assert.ok(zip.file('voice/'+voice.audioKey));
 await page.locator('[data-upload="restore"]').setInputFiles(file);await idle();data=await read();assert.equal(data.fragments.length,6);assert.equal(new Set(data.fragments.map(n=>n.id)).size,6);assert.equal(data.fragments.filter(n=>n.audioKey).length,2);assert.equal(data.fragmentPlans.length,2);
 await nav();await page.screenshot({path:path.resolve(__dirname,'../test-output/灵感速记_桌面.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);assert.deepEqual(errors,[]);
 console.log('PASS fragments: legacy migration/dedupe, draft/reload, real fake-device recording+playback+download, mocked speech, permission denial, mocked refine/combine/provenance, scope isolation, voice ZIP restore, mobile. No real microphone or model used.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
