// Isolated browser profile; verifies the unconfigured/offline-safe mobile companion and desktop handoff.
const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/mobile-config.js',route=>route.fulfill({contentType:'application/javascript',body:'window.JINHUA_MOBILE_CONFIG={};'}));
  await page.goto('http://127.0.0.1:8787/mobile.html');assert.equal(await page.getByRole('heading',{name:'今天先看 3 个视觉方向。'}).count(),1);assert.equal(await page.locator('.radar-mobile-card').count(),3);assert.ok(await page.locator('.radar-mobile-card.visual-first').count()>=2);assert.ok(await page.locator('.radar-mobile-visual img').count()>=2);assert.equal(await page.locator('.radar-mobile-cn').count(),3);assert.equal(await page.getByRole('button',{name:'收下这个选题'}).count(),3);assert.equal(await page.getByRole('button',{name:'添加每日日历提醒'}).count(),1);assert.equal(await page.locator('.radar-refresh-top').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
  const before=await page.locator('.radar-mobile-card h2').allTextContents();await page.locator('.radar-refresh-top').click();await page.waitForFunction(old=>JSON.stringify([...document.querySelectorAll('.radar-mobile-card h2')].map(node=>node.textContent))!==old,JSON.stringify(before));assert.equal(await page.evaluate(()=>scrollY),0);
  await page.goto('http://127.0.0.1:8787/mobile.html?title=ShotDeck%E5%8F%82%E8%80%83&url=https%3A%2F%2Fshotdeck.com%2Fboards%2Fdemo&text=%E5%96%9C%E6%AC%A2%E8%BF%99%E4%B8%AA%E4%BD%8E%E9%A5%B1%E5%92%8C%E9%80%86%E5%85%89');
  assert.equal(await page.locator('#capture-title').inputValue(),'ShotDeck参考');assert.equal(await page.locator('#capture-url').inputValue(),'https://shotdeck.com/boards/demo');assert.equal(await page.locator('#capture-body').inputValue(),'喜欢这个低饱和逆光');assert.match(await page.locator('#capture-file').getAttribute('accept'),/application\/pdf/);
  await page.getByRole('button',{name:/视频/}).click();assert.equal(await page.locator('#capture-file').getAttribute('accept'),'video/*');assert.equal(await page.locator('#capture-title').inputValue(),'ShotDeck参考');
  await page.getByRole('button',{name:/链接/}).click();assert.equal(await page.locator('#capture-url').inputValue(),'https://shotdeck.com/boards/demo');
  await page.getByRole('button',{name:/文字/}).click();await page.locator('#capture-title').fill('离线测试灵感');await page.locator('#capture-body').fill('一束光从走廊尽头进入。');await page.getByRole('button',{name:'保存到随身收件箱'}).click();await page.waitForFunction(()=>document.querySelector('#mobile-toast').innerText.includes('已保存在此设备'));
  assert.match(await page.locator('#sync-state').textContent(),/1条本机草稿/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
  const manifest=await (await page.request.get('http://127.0.0.1:8787/mobile.webmanifest')).json();assert.equal(manifest.share_target.params.url,'url');
  assert.deepEqual(errors,[]);await browser.close();console.log('PASS: mobile daily radar, reminder entry, offline capture, responsive layout, and desktop inbox setup state.');
})().catch(error=>{console.error(error);process.exit(1);});
