const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');
const C=require('../studio-core');const P=require('../studio-ppt');const PptxGenJS=require('pptxgenjs');const JSZip=require('jszip');
const dir=path.resolve(__dirname,'../test-output');fs.mkdirSync(dir,{recursive:true});
test('实际PPT文件：可编辑文字、3张内嵌图、3段原生8秒视频',async()=>{
 cp.execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=320x240:rate=24','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','8','-c:v','libx264','-preset','ultrafast','-c:a','aac','-pix_fmt','yuv420p','-y',path.join(dir,'fixture.mp4')]);
 cp.execFileSync('ffmpeg',['-v','error','-i',path.join(dir,'fixture.mp4'),'-frames:v','1','-y',path.join(dir,'fixture.png')]);
 const image='data:image/png;base64,'+fs.readFileSync(path.join(dir,'fixture.png')).toString('base64');const video='data:video/mp4;base64,'+fs.readFileSync(path.join(dir,'fixture.mp4')).toString('base64');
 const t=C.topic('软件验收样片（测试图形，非AI作品）');for(const[k,label]of C.QUICK)t.quick.fields[k]=label+'：以夜间直播工作场景为叙事基础。测试文案，仅用于核验PPT排版和导出，不作为产品性能证据。';
 for(const s of t.quick.images)C.putVersion(s,{kind:'image',localId:'fixture.png',verified:true,source:'test-fixture'});for(const[k]of C.PHASES)C.putVersion(t.quick.videos[k],{kind:'video',localId:'fixture.mp4',verified:true,source:'ai',provenance:'仅用于模拟AI接口返回的测试图形',duration:8,width:320,height:240});
 const ppt=await P.buildDeck(PptxGenJS,t,'topic',[],a=>a.kind==='image'?image:video);const bytes=await ppt.write({outputType:'nodebuffer'});fs.writeFileSync(path.join(dir,'软件验收样片_非AI作品.pptx'),bytes);const zip=await JSZip.loadAsync(bytes);const slides=Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n));assert.equal(slides.length,14);assert.equal(Object.keys(zip.files).filter(n=>n.endsWith('.mp4')).length,3);assert.match(await zip.file('ppt/slides/slide2.xml').async('string'),/创意大纲/);assert.match(await zip.file('ppt/slides/_rels/slide12.xml.rels').async('string'),/relationships\/video/);assert.ok(Object.keys(zip.files).some(n=>/ppt\/media\/.*png/.test(n)));
 const project=C.project('6条专场验收');for(const[k]of C.SESSION)project.fields[k]='整体方案';const topics=Array.from({length:6},(_,i)=>({...C.clone(t),id:'test-'+i}));project.topicIds=topics.map(t=>t.id);const sp=await P.buildDeck(PptxGenJS,project,'project',topics,a=>a.kind==='image'?image:video);const z=await JSZip.loadAsync(await sp.write({outputType:'nodebuffer'}));assert.equal(Object.keys(z.files).filter(n=>n.endsWith('.mp4')).length,18);
 t.quick.approved={fields:C.clone(t.quick.fields)};for(const[k]of C.DEEP)t.deep.fields[k]='执行内容';t.deep.shots=C.validateShots({shots:Array.from({length:25},()=>({visual:'测试画面',camera:'中景',duration:2}))});for(const s of t.deep.shots)C.putVersion(s.image,{kind:'image',localId:'fixture.png',source:'ai',verified:true});t.deep.film={kind:'video',localId:'fixture.mp4',source:'ai-assembly',verified:true,duration:50,fingerprint:C.shotFingerprint(t.deep.shots),bgmId:null};const dp=await P.buildDeck(PptxGenJS,t,'deep',[],a=>a.kind==='image'?image:video);const dz=await JSZip.loadAsync(await dp.write({outputType:'nodebuffer'}));assert.equal(Object.keys(dz.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)).length,65);
});
test('未齐备汇报阻止导出',async()=>assert.rejects(P.buildDeck(PptxGenJS,C.topic(),'topic',[],()=>''),/不能导出/));
