// Isolated browser storage. AI text is mocked; no live provider calls or user data writes.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8787/');await page.getByRole('button',{name:'新建单条脚本',exact:true}).click();await page.locator('#new-title').fill('冠军篇 · 汇报模式验收');await page.locator('#new-idea').fill('仅用于功能测试');await page.getByRole('button',{name:'创建并开始',exact:true}).click();
 const section=page.locator('.report-tools');for(const name of ['老板决策版','完整策划版','单条执行版'])assert.equal(await section.getByRole('button',{name,exact:true}).count(),1);
 await section.locator('summary').click();
 for(const[k,value]of Object.entries({recommendation:'从隧道的犹疑走向团队承诺',reason:'沿用用户提供的冠军篇创作方向',confirmed:'用户已提供冠军篇剧本',decisions:'确认结尾口号与场地规模'})){const f=page.locator('[data-field="topics.0.report.'+k+'"]');await f.fill(value);await f.blur();}
 await page.route('**/api/chat',async route=>{const prompt=route.request().postDataJSON().prompt;assert.match(prompt,/不要把需求、假设或AI建议宣称为已确认事实/);await route.fulfill({json:{text:JSON.stringify({recommendation:'AI不应覆盖主推',reason:'AI不应覆盖理由',confirmed:'AI伪造确认',pending:'场地待确认',alternatives:'',production:'拍摄日期待确认',decisions:'AI不应覆盖拍板事项'})}});});
 await section.getByRole('button',{name:'AI提炼汇报要点',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.job'));
 await section.getByRole('button',{name:'老板决策版',exact:true}).click();assert.equal(await page.getByRole('button',{name:'下载老板决策版',exact:true}).isEnabled(),true);assert.match(await page.getByRole('dialog').innerText(),/方向讨论稿/);assert.match(await page.getByRole('dialog').innerText(),/本次需要拍板/);
 await page.screenshot({path:path.resolve(__dirname,'../test-output/PPT三种导出_预览.png')});const pending=page.waitForEvent('download');await page.getByRole('button',{name:'下载老板决策版',exact:true}).click();const result=await pending;assert.match(result.suggestedFilename(),/老板决策版_方向讨论稿/);await page.waitForFunction(()=>!document.querySelector('.job'));
 const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('lance_studio_v2_xinxuan')));assert.equal(stored.topics[0].report.confirmed,'用户已提供冠军篇剧本');assert.equal(stored.topics[0].report.recommendation,'从隧道的犹疑走向团队承诺');assert.equal(stored.exports[0].draft,true);assert.equal(stored.exports[0].mode,'decision');
 for(const name of ['完整策划版','单条执行版']){await section.getByRole('button',{name,exact:true}).click();assert.equal(await page.getByRole('button',{name:'下载'+name,exact:true}).isDisabled(),true);await page.getByRole('button',{name:'关闭',exact:true}).click();}
 await page.reload();await page.getByRole('button',{name:'成果与备份',exact:true}).click();assert.match(await page.locator('#view').innerText(),/老板决策版 · 方向讨论稿/);const again=page.waitForEvent('download');await page.getByRole('button',{name:'重新下载',exact:true}).click();assert.equal((await again).suggestedFilename(),result.suggestedFilename());
 await page.getByRole('button',{name:'工作台',exact:true}).click();await page.getByRole('button',{name:'新建专场',exact:true}).click();await page.locator('#new-title').fill('测试专场');await page.getByRole('button',{name:'创建并开始',exact:true}).click();assert.equal(await section.getByRole('button',{name:'单条执行版',exact:true}).count(),0);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);assert.deepEqual(errors,[]);
 console.log('PASS: report modes, draft label, required-media gates, editable facts, mocked AI preserves input, archive and redownload names, project mode, mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
