const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../studio-core');const R=require('../studio-reverse');
const raw=()=>({fields:Object.fromEntries(R.FIELDS.map(([k,l])=>[k,l+'测试内容'])),shots:[{frameIndex:0,visual:'可见人物',camera:'中景',dialogue:'待核对',note:'仅依据采样画面'}]});
test('已存在新版数据也能迁移旧反推记录且去重，不改变旧数据',()=>{const old=[{id:7,title:'过往作品',creativeOutline:'原创意',storyboard:[{shot:1,visual:'原分镜'}],videoUrl:'blob:expired'}];const before=JSON.stringify(old);const db={topics:[]};R.migrate(db,old);R.migrate(db,old);assert.equal(db.reverse.length,1);assert.equal(db.reverse[0].analysis.fields.outline,'原创意');assert.equal(db.reverse[0].analysis.legacyStoryboard.length,1);assert.equal(db.reverse[0].video,null);assert.equal(JSON.stringify(old),before);assert.equal(R.migrate({},[]).reverse.length,0);});
test('反推必须有字段和实际帧证据，错误结果不覆盖原分析',()=>{const r=R.create('片');r.frames=[{timestamp:2,localId:'frame'}];R.accept(r,raw());const old=JSON.stringify(r.analysis);const bad=raw();bad.shots[0].frameIndex=12;assert.throws(()=>R.accept(r,bad),/证据/);assert.equal(JSON.stringify(r.analysis),old);assert.equal(r.history.length,0);R.accept(r,raw());assert.equal(r.history.length,1);assert.equal(r.analysis.shots[0].timestamp,2);});
test('转选题保留创意和来源，不冒充快速媒体或25镜成片',()=>{const r=R.create('片');r.projectId='project';r.frames=[{timestamp:1}];R.accept(r,raw());const t=R.toTopic(r);assert.equal(t.projectId,'project');assert.equal(t.quick.fields.outline,r.analysis.fields.outline);assert.equal(t.sourceReverse.id,r.id);assert.equal(C.quickStatus(t).ready,false);assert.equal(C.quickStatus(t).videos,0);assert.equal(t.deep.shots.length,0);});
test('新版记录JSON导入不丢分析，坏结构不部分写入',()=>{const r=R.create('片');r.frames=[{timestamp:1}];R.accept(r,raw());const db={reverse:[]};R.importRecords(db,{version:2,reverse:[r]});assert.deepEqual(db.reverse[0].analysis,r.analysis);assert.notEqual(db.reverse[0].id,r.id);assert.throws(()=>R.importRecords(db,{version:2,reverse:[r,{}]}),/不完整/);assert.equal(db.reverse.length,1);});
test('提示限定为采样推断，音轨和25镜不伪造',()=>{const r=R.create('片');const p=R.prompt(r);assert.match(p,/没有音轨/);assert.match(p,/不强行补25镜/);assert.match(p,/台词与配乐必须标为待核对/);});
test('喜欢的参考片与历史项目使用不同反推任务，均要求意图、概念和脚本',()=>{const reference=R.create('喜欢的片'),archive=R.create('旧项目','archive');assert.equal(reference.purpose,'reference');assert.equal(archive.purpose,'archive');assert.match(R.prompt(reference),/可借鉴机制/);assert.match(R.prompt(reference),/不得照抄/);assert.match(R.prompt(archive),/原方案遗失/);assert.match(R.prompt(archive),/可归档成果/);assert.ok(R.FIELDS.some(([k])=>k==='intent'));assert.ok(R.FIELDS.some(([k])=>k==='concept'));assert.ok(R.FIELDS.some(([k])=>k==='script'));});
test('补充文档与图片进入反推上下文，视觉输入总数不超过12',()=>{const r=R.create('有资料的片');r.sourceLink='https://example.com/work';r.sourceInfo={title:'公开页标题',description:'页面摘要'};r.frames=Array.from({length:12},(_,i)=>({localId:'frame-'+i,timestamp:i}));r.supportingFiles=[{name:'现场照.jpg',kind:'image',localId:'support-image',includeInAnalysis:true,note:'灯位证据'},{name:'旧脚本.txt',kind:'text',localId:'support-text',includeInAnalysis:true,extractedText:'已核对的旧脚本正文'},{name:'未选图.jpg',kind:'image',localId:'ignored',includeInAnalysis:false}];const plan=R.referencePlan(r),prompt=R.prompt(r);assert.equal(plan.ids.length,12);assert.ok(plan.ids.includes('support-image'));assert.ok(!plan.ids.includes('ignored'));assert.match(prompt,/已核对的旧脚本正文/);assert.match(prompt,/公开页标题/);assert.match(prompt,/supportImage/);});
