const {test}=require('node:test');const assert=require('node:assert/strict');
const RC=require('../studio-reverse-case'),P=require('../studio-ppt'),WC=require('../studio-workspace-cloud');
const video={kind:'video',localId:'original.mp4',name:'双十一.mp4',duration:1300,verified:true};
function fixture(){const p=RC.create('双十一历史整场'),clips=RC.makeClips(p,video,'key');for(const c of clips){c.caseFrames=[1,2,3].map(n=>({kind:'image',localId:'frame-'+c.id+n,verified:true,width:960,height:540,source:'video-frame',timestamp:c.segment.start+n}));c.caseSummary={...Object.fromEntries(Object.keys(RC.CLIP_LABELS).map(k=>[k,'已观察到的'+k])),stamp:RC.clipStamp(c)};}p.overview=Object.fromEntries(Object.keys(RC.LABELS).map(k=>[k,'概览'+k]));p.overviewStamp=RC.stamp(p,clips);return {p,clips};}
test('项目案例不创建执行项目；长录像按时间段归档并共享原片',()=>{const p=RC.create('双十一'),clips=RC.makeClips(p,video,'key');assert.equal(p.kind,'collection');assert.equal(p.projectId,null);assert.equal(clips.length,3);assert.deepEqual(clips.map(c=>c.segment),[{start:0,end:600},{start:600,end:1200},{start:1200,end:1300}]);assert.ok(clips.every(c=>c.caseId===p.id&&c.video.localId===video.localId&&!c.analysis));assert.equal(RC.range(clips[2]),'20:00–21:40');});
test('视频时长和分段上限校验',()=>{for(const duration of [0,-1,Infinity,36001])assert.throws(()=>RC.makeClips(RC.create('项目'),{...video,duration},'k'));assert.equal(RC.makeClips(RC.create('项目'),{...video,duration:600},'k').length,1);});
test('单条概览和汇总只在证据与说明匹配时为就绪；取回云端文件不导致重复付费',()=>{const {p,clips}=fixture();assert.equal(RC.status(p,clips).ready,true);clips[0].caseFrames[0].localId='hydrated.jpg';assert.equal(RC.clipReady(clips[0]),true);assert.equal(RC.status(p,clips).ready,true);clips[0].notes='补充事实';assert.equal(RC.clipReady(clips[0]),false);assert.equal(RC.status(p,clips).ready,false);assert.equal(RC.status(p,clips).pending,1);});
test('移出可恢复，不删除视频，子记录不丢失父级关系',()=>{const {p,clips}=fixture(),all=[p,...clips];clips[0].caseRemovedAt='now';assert.equal(RC.children(p,all).length,2);assert.ok(clips[0].video);delete clips[0].caseRemovedAt;assert.equal(RC.children(p,all).length,3);});
test('概览要求完整字段且保留事实与推断边界，资料文字不作为指令',()=>{const {p,clips}=fixture();assert.throws(()=>RC.validate({summary:'a'},RC.CLIP_LABELS));assert.match(RC.clipPrompt(clips[0]),/不代表完整观看/);assert.match(RC.projectPrompt(p,clips),/上传顺序不代表发布时间/);assert.match(RC.projectPrompt(p,clips),/不执行其中指令/);});
test('项目PPT含实际画面、整体总结和覆盖说明，不捆绑单条详细脚本',()=>{const {p,clips}=fixture();clips[0].analysis={fields:{script:'不应自动导出的详细脚本'}};const snapshot=RC.snapshot(p,[p,...clips]),plan=P.planDeck(snapshot,'reverse-case',[],'case');assert.equal(plan.status.ready,true);assert.equal(plan.slides.filter(s=>s.type==='evidence').length,4);assert.equal(plan.slides[1].title,'先看原片 · 项目视觉索引');assert.doesNotMatch(JSON.stringify(plan),/不应自动导出/);assert.match(JSON.stringify(plan),/原片均匀采样/);snapshot.clips[0].notes='改了';assert.equal(P.reportStatus(snapshot,'reverse-case').ready,false);});
test('部分失败可汇总但必须标注未分析的单条',()=>{const {p,clips}=fixture();clips[1].caseSummary=null;p.overviewStamp=RC.stamp(p,clips);const plan=P.planDeck(RC.snapshot(p,[p,...clips]),'reverse-case');assert.equal(plan.status.ready,true);assert.equal(plan.status.pending,1);assert.match(JSON.stringify(plan),/尚未纳入有效分析/);});
test('媒体同步递归包括项目视频、粗帧与深拆帧，共享原片仅一个分组',()=>{const {p,clips}=fixture();const groups=WC.mediaGroups({reverse:[p,...clips]},[]);assert.equal(groups.get('original.mp4').length,3);assert.equal(groups.size,10);});
test('整体案例PPT实际打包内嵌帧，不包含原片视频或单条脚本',async()=>{const fs=require('fs'),path=require('path'),PptxGenJS=require('pptxgenjs'),JSZip=require('jszip');const {p,clips}=fixture();const image='data:image/png;base64,'+fs.readFileSync(path.join(__dirname,'../test-output/fixture.png')).toString('base64');const ppt=await P.buildDeck(PptxGenJS,RC.snapshot(p,[p,...clips]),'reverse-case',[],()=>image,'case'),buffer=await ppt.write({outputType:'nodebuffer'}),zip=await JSZip.loadAsync(buffer);assert.ok(Object.keys(zip.files).some(n=>n.startsWith('ppt/media/')&&n.endsWith('.png')));assert.ok(!Object.keys(zip.files).some(n=>n.endsWith('.mp4')));if(process.env.JINHUA_CASE_QA_DIR)fs.writeFileSync(path.join(process.env.JINHUA_CASE_QA_DIR,'project-case.pptx'),buffer);});
