// Isolated test browser; mock only paid AI response, use real upload/frame extraction.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');const R=require('../studio-reverse');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{if(localStorage.getItem('reverse-test-seeded'))return;localStorage.setItem('reverse-test-seeded','1');localStorage.setItem('lance_studio_v2_xinxuan',JSON.stringify({version:2,topics:[],projects:[],assets:[],exports:[],preferences:''}));localStorage.setItem('xuan_ti_ku_reverse_xinxuan',JSON.stringify([{id:123,title:'历史反推测试稿',creativeOutline:'原来的大纲',videoUrl:'blob:expired',storyboard:[{shot:1,visual:'原始镜头'}]}]));});
 await page.goto('http://127.0.0.1:8787/');await page.getByRole('button',{name:'视频反推创意',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'历史反推测试稿',exact:true}).count(),1);
 await page.reload();await page.getByRole('button',{name:'视频反推创意',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'历史反推测试稿',exact:true}).count(),1);
 await page.locator('#scope').selectOption('personal');await page.getByRole('button',{name:'视频反推创意',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'历史反推测试稿',exact:true}).count(),0);await page.locator('#scope').selectOption('xinxuan');await page.getByRole('button',{name:'视频反推创意',exact:true}).click();
 await page.getByRole('button',{name:'建立视频反推',exact:true}).click();await page.locator('#reverse-purpose').selectOption('archive');await page.locator('#reverse-title').fill('【验收】原视频反推');await page.getByRole('button',{name:'创建反推案例',exact:true}).click();
 await page.route('**/api/link/import',route=>route.fulfill({json:{url:'https://example.com/work',finalUrl:'https://example.com/work',title:'模拟公开作品页',description:'页面公开摘要',siteName:'example.com',asset:null,notice:'已解析页面信息；请手动上传原片。'}}));await page.locator('[data-field="reverse.1.sourceLink"]').fill('分享：https://example.com/work');await page.getByRole('button',{name:'解析链接',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.job'));assert.ok(await page.getByText('模拟公开作品页',{exact:true}).count());await page.unroute('**/api/link/import');
 await page.locator('[data-upload="reverse-support"]').setInputFiles([{name:'旧脚本.txt',mimeType:'text/plain',buffer:Buffer.from('已核对的历史脚本正文')},{name:'现场照.png',mimeType:'image/png',buffer:require('node:fs').readFileSync(path.resolve(__dirname,'../test-output/fixture.png'))}]);await page.waitForFunction(()=>!document.querySelector('.job'));let reverseState=await page.evaluate(()=>JSON.parse(localStorage.getItem('lance_studio_v2_xinxuan')).reverse[1]);assert.equal(reverseState.supportingFiles.length,2);assert.equal(reverseState.supportingFiles[0].extractedText,'已核对的历史脚本正文');const supportImageId=reverseState.supportingFiles[1].localId;
 await page.locator('[data-upload="reverse-video"]').setInputFiles(path.resolve(__dirname,'../test-output/fixture.mp4'));await page.waitForFunction(()=>!document.querySelector('.job'));let requests=0;
 await page.route('**/api/chat',async route=>{requests++;const body=route.request().postDataJSON();assert.equal(body.references.length,12);assert.ok(body.references.includes(supportImageId));assert.match(body.prompt,/没有可用音轨转写/);assert.match(body.prompt,/历史项目/);assert.match(body.prompt,/已核对的历史脚本正文/);assert.match(body.prompt,/模拟公开作品页/);const payload={fields:Object.fromEntries(R.FIELDS.map(([k,l])=>[k,'【模拟AI输出】'+l])),shots:[{frameIndex:0,visual:'测试图形',camera:'固定画面',dialogue:'无字幕，声音待核实',note:'不是实际AI作品'}]};await route.fulfill({json:{text:JSON.stringify(payload)}});});
 await page.getByRole('button',{name:'AI反推创意与脚本',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.job'),null,{timeout:60000});assert.equal(requests,1);assert.equal(await page.locator('[data-field="reverse.1.analysis.fields.intent"]').inputValue(),'【模拟AI输出】创作意图（推测）');assert.equal(await page.locator('[data-field="reverse.1.analysis.fields.concept"]').inputValue(),'【模拟AI输出】核心创作概念');assert.equal(await page.locator('[data-field="reverse.1.analysis.fields.outline"]').inputValue(),'【模拟AI输出】创意大纲');assert.equal(await page.locator('.grid img').count(),12);await page.getByRole('button',{name:'保存完整反推档案',exact:true}).click();const scoped=await page.evaluate(()=>({work:JSON.parse(localStorage.getItem('lance_studio_aesthetic_xinxuan')||'[]'),personal:JSON.parse(localStorage.getItem('lance_studio_aesthetic_personal')||'[]')}));assert.equal(scoped.work.filter(a=>a.sourceReverseId).length,1);assert.equal(scoped.work.find(a=>a.sourceReverseId).category,'历史项目重建');assert.equal(scoped.personal.filter(a=>a.sourceReverseId).length,0);await page.screenshot({path:path.resolve(__dirname,'../test-output/视频反推_桌面.png')});
 await page.getByRole('button',{name:'重新反推（保留旧版）',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.job'));assert.equal(await page.getByRole('button',{name:'查看旧版',exact:true}).count(),1);
 await page.unroute('**/api/chat');await page.route('**/api/chat',r=>r.fulfill({status:400,json:{error:'模拟上游失败'}}));await page.getByRole('button',{name:'重新反推（保留旧版）',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.job'));assert.equal(await page.locator('[data-field="reverse.1.analysis.fields.outline"]').inputValue(),'【模拟AI输出】创意大纲');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'下载反推记录JSON',exact:true}).click();assert.ok((await downloadPromise).suggestedFilename().endsWith('.json'));
 await page.getByRole('button',{name:'保存为新选题',exact:true}).click();assert.equal(await page.locator('[data-field="topics.0.quick.fields.outline"]').inputValue(),'【模拟AI输出】创意大纲');assert.equal(await page.getByRole('button',{name:'确认完整交付，进入深化'}).isDisabled(),true);
 await page.getByRole('button',{name:'视频反推创意',exact:true}).click();await page.locator('[data-reverse-search]').fill('【验收】');assert.equal(await page.getByRole('button',{name:'打开反推',exact:true}).count(),1);await page.getByRole('button',{name:'打开反推',exact:true}).click();await page.getByRole('button',{name:'保存场景参考',exact:true}).click();assert.match(await page.locator('[data-field="assets.0.analysis"]').inputValue(),/模拟AI输出/);
 await page.getByRole('button',{name:'视频反推创意',exact:true}).click();await page.getByRole('button',{name:'打开反推',exact:true}).nth(1).click();await page.getByRole('button',{name:'保存服装参考',exact:true}).click();assert.equal(await page.locator('video').count(),1);
 await page.reload();await page.getByRole('button',{name:'视频反推创意',exact:true}).click();assert.equal(await page.getByRole('button',{name:'打开反推',exact:true}).count(),2);await page.getByRole('button',{name:'打开反推',exact:true}).nth(1).click();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);assert.deepEqual(errors,[]);await browser.close();console.log('PASS reverse: link metadata parsing, manual supporting documents/images with extracted text, dual purpose historical reconstruction, scope-isolated archive, real upload/12 frames, mocked analysis, history/error preservation, JSON, topic and asset reuse, mobile.');
})().catch(e=>{console.error(e);process.exit(1);});
