// Isolated test browser; mock only paid AI response, use real upload/frame extraction.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');const R=require('../studio-reverse');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{if(localStorage.getItem('reverse-test-seeded'))return;localStorage.setItem('reverse-test-seeded','1');localStorage.setItem('lance_studio_v2_xinxuan',JSON.stringify({version:2,topics:[],projects:[],assets:[],exports:[],preferences:'',reverse:[{id:'legacy-copy',legacyId:'123',legacy:{id:123},title:'历史反推测试稿'}]}));localStorage.setItem('xuan_ti_ku_reverse_xinxuan','[{"id":123,"title":"旧版JSON"}]');});
 await page.goto('http://127.0.0.1:8787/');await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('button',{name:/视频反推/}).click();assert.equal(await page.getByText('历史反推测试稿',{exact:true}).count(),0);assert.equal(await page.getByText(/导入.*JSON/).count(),0);assert.equal(await page.evaluate(()=>localStorage.getItem('xuan_ti_ku_reverse_xinxuan')),null);
 await page.getByRole('button',{name:'建立视频反推',exact:true}).click();await page.locator('#reverse-purpose').selectOption('archive');await page.locator('#reverse-title').fill('【验收】原视频反推');await page.getByRole('button',{name:'创建反推案例',exact:true}).click();
 await page.locator('[data-upload="reverse-video"]').first().setInputFiles(path.resolve(__dirname,'../test-output/fixture.mp4'));await page.waitForFunction(()=>!document.querySelector('.job'));await page.getByRole('button',{name:'提取12帧',exact:true}).last().click();await page.waitForFunction(()=>!document.querySelector('.job'),null,{timeout:60000});let requests=0;
 await page.route('**/api/chat',async route=>{requests++;const body=route.request().postDataJSON();assert.equal(body.references.length,12);assert.match(body.prompt,/没有可用音轨转写/);assert.match(body.prompt,/历史项目/);assert.match(body.prompt,/不提议或生成新的参考图/);const payload={fields:Object.fromEntries(R.FIELDS.map(([k,l])=>[k,'【模拟AI输出】'+l])),shots:Array.from({length:12},(_,i)=>({frameIndex:i,story:`故事段落${i+1}`,narrativeRole:i===0?'开场':'发展',action:'人物行动',emotion:'情绪递进',visual:'测试图形',camera:'固定画面',dialogue:'无字幕，声音待核实',transition:'顺接下一段',evidence:'画面可见，故事为推断',note:'不是实际AI作品'})),wardrobeReferences:[{frameIndex:0,name:'测试全身造型',description:'黑色上装与长裤',fullBodyReason:'人物从头到脚完整入画'}]};await route.fulfill({json:{text:JSON.stringify(payload)}});});
 await page.getByRole('button',{name:'AI反推完整故事',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.job'),null,{timeout:60000});assert.equal(requests,1);assert.equal(await page.locator('[data-field="reverse.0.analysis.fields.intent"]').inputValue(),'【模拟AI输出】创作意图（推测）');assert.equal(await page.locator('[data-field="reverse.0.analysis.fields.concept"]').inputValue(),'【模拟AI输出】核心创作概念');assert.equal(await page.locator('[data-field="reverse.0.analysis.fields.outline"]').inputValue(),'【模拟AI输出】创意大纲');assert.equal(await page.locator('.reverse-frame-grid img').count(),12);assert.equal(await page.locator('.reverse-story-card').count(),12);assert.equal(await page.getByRole('button',{name:/保存场景参考|保存服装参考|保存为新选题/}).count(),0);await page.screenshot({path:path.resolve(__dirname,'../test-output/视频反推_桌面.png')});
 await page.unroute('**/api/chat');await page.route('**/api/chat',r=>r.fulfill({status:400,json:{error:'模拟上游失败'}}));await page.getByRole('button',{name:'重新反推',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.job'));assert.equal(await page.locator('[data-field="reverse.0.analysis.fields.outline"]').inputValue(),'【模拟AI输出】创意大纲');
 await page.route('**/api/reverse/pdf',route=>route.fulfill({status:200,contentType:'application/pdf',body:Buffer.concat([Buffer.from('%PDF-1.4\n'),Buffer.alloc(1400),Buffer.from('\n%%EOF')])}));await page.getByRole('button',{name:'预览PDF',exact:true}).last().click();await page.waitForFunction(()=>!document.querySelector('.job'));assert.equal(await page.locator('.reverse-pdf-preview iframe').count(),1);await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('button',{name:/视频反推/}).click();await page.locator('[data-reverse-search]').fill('【验收】');assert.equal(await page.getByRole('button',{name:'继续',exact:true}).count(),1);await page.getByRole('button',{name:'继续',exact:true}).click();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);assert.deepEqual(errors,[]);await browser.close();console.log('PASS reverse: original video, 12 source frames, detailed story segments, text-only reverse workflow, PDF preview and mobile layout.');
})().catch(e=>{console.error(e);process.exit(1);});
