// Isolated storage, mocked text/ASR/retrieval: never calls a paid provider.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],mediaCalls=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/\/api\/(image|video)$/.test(r.url()))mediaCalls.push(r.url());});
 await page.goto('http://127.0.0.1:8000/');await page.getByRole('button',{name:'新建专场',exact:true}).click();await page.locator('#new-title').fill('中秋 · 七条片验收');await page.locator('#new-count').fill('7');await page.locator('#new-idea').fill('4条预热视频，2条自述，1条祝福。');await page.getByRole('button',{name:'创建并开始',exact:true}).click();
 assert.equal(await page.locator('[data-action="project-all"]').count(),0);
 let expected=7,calls=0,bad=false;
 await page.route('**/api/chat',async route=>{const body=route.request().postDataJSON();assert.equal(body.purpose,'director');assert.equal(body.model,undefined);assert.equal(route.request().headers().authorization,undefined);assert.match(body.prompt,new RegExp('只补充缺少的'+expected+'条'));calls++;await route.fulfill({json:{text:JSON.stringify({fields:Object.fromEntries(['outline','description','meaning','scene','art','atmosphere','camera'].map(k=>[k,'测试方向：'+k])),stories:Array.from({length:bad?expected+1:expected},(_,i)=>({title:'故事'+calls+'-'+i,idea:'仅测试用方向与分工，拍摄条件待确认'}))})}});});
 await page.locator('[data-action="project-text"]').click();await page.waitForFunction(()=>!document.querySelector('.job'));assert.equal(calls,1);
 let stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('lance_studio_v2_xinxuan')));assert.equal(stored.projects[0].targetCount,7);assert.equal(stored.topics.length,7);assert.equal(stored.projects[0].topicIds.length,7);assert.equal(mediaCalls.length,0);
 assert.match(await page.locator('#view').innerText(),/方向汇报可讨论/);
 await page.locator('.report-tools [data-mode="decision"]').click();assert.equal(await page.locator('[data-action="report-download"]').isEnabled(),true);
 const pending=page.waitForEvent('download');await page.locator('[data-action="report-download"]').click();const download=await pending;await download.saveAs(path.resolve(__dirname,'../test-output/七条方向汇报_功能验收.pptx'));await page.waitForFunction(()=>!document.querySelector('.job'));
 await page.locator('.report-tools [data-mode="full"]').click();assert.equal(await page.locator('[data-action="report-download"]').isDisabled(),true);await page.locator('[data-action="close"]').click();assert.equal(mediaCalls.length,0);
 await page.locator('[data-session-count]').fill('6');await page.locator('[data-session-count]').blur();assert.match(await page.locator('#notification').innerText(),/不能少于/);
 await page.locator('[data-session-count]').fill('8');await page.locator('[data-session-count]').blur();expected=1;await page.locator('[data-action="project-text"]').click();await page.waitForFunction(()=>!document.querySelector('.job'));stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('lance_studio_v2_xinxuan')));assert.equal(stored.topics.length,8);assert.equal(stored.topics[0].title,'故事1-0');
 await page.locator('[data-session-count]').fill('9');await page.locator('[data-session-count]').blur();bad=true;await page.locator('[data-action="project-text"]').click();await page.waitForFunction(()=>!document.querySelector('.job'));assert.match(await page.locator('#notification').innerText(),/必须补充1条/);stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('lance_studio_v2_xinxuan')));assert.equal(stored.topics.length,8);
 await page.locator('[data-action="workflow-stage"][data-stage="full"]').click();assert.equal(await page.locator('[data-action="project-all"]').count(),1);
 await page.locator('#view [data-action="topic"]').first().click();assert.equal(await page.getByRole('heading',{name:'视频封面推荐 · A/B/C三套',exact:true}).count(),0);await page.locator('[data-action="workflow-stage"][data-stage="full"]').click();assert.equal(await page.getByRole('heading',{name:'视频封面推荐 · A/B/C三套',exact:true}).count(),1);
 await page.locator('[data-action="settings"]').click();assert.equal(await page.locator('#cfg-token').count(),0);assert.match(await page.getByRole('dialog').innerText(),/Doubao-Seed-2.1-turbo/);await page.locator('[data-action="close"]').click();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await page.screenshot({path:path.resolve(__dirname,'../test-output/分阶段汇报_移动端.png')});assert.deepEqual(errors,[]);assert.equal(mediaCalls.length,0);
 console.log('PASS: 7-story direction report/PPT, no media generation, flexible counts, incremental planning, atomic invalid response, final gate, server-only settings, mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
